### ISSUE TITLE
"Details"-Icon in Image-Toolbar

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1025]
In der Steckbrief-Ansicht wird aktuell die 🔍 angezeigt, um die Detailseite aufzurufen. Da hierüber auch die Bild-Audios zugänglich sind, sollte hier ein allgemeineres Icon stehen. Vorschläge?

https://fonts.google.com/icons?selected=Material+Icons

**Comment by kerstinhartmann** [comment]
Ich hab spontan an sowas gedacht: 
https://fonts.google.com/icons?selected=Material%20Icons%3Amore_horiz

**Comment by anhnguyen-98** [comment]
close via PR #1084
