### ISSUE TITLE
Komisches Verhalten der Zoom-Buttons Image-Toolbar (mobil)

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#1040]
Die Zoom-Buttons & der Home-Button bleiben ausgegraut, nachdem man sie benutzt hat und werden immer "ausgegrauter"/dunkler, je öfter sie benutzt werden. Der Copyright-Button verhält sich wie gewollt und ist nur für den "Klick-Moment" ausgegraut. 
(Der Fehler trat bisher nur auf meinem Handy mit Android 6.0.1 und Firefox 68.6.0 auf.)

**Comment by kerstinhartmann** [comment]
![Zoombuttons_ImageToolbar](https://user-images.githubusercontent.com/66634630/121363992-af844e80-c937-11eb-8651-3580bd332868.jpg)

**Comment by sheepyhollow** [comment]
Wir müssten das nochmal verifizieren und auf anderen Geräten sehen. Wenn es nur bei einem Gerät auftritt, ist es vielleicht kein allgemeiner Fehler.
