### ISSUE TITLE
Image Toolbar in der Slideshow

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1044]
Aktuell werden Bilder in der Slideshow einfach "nur so" angezeigt.
Der Zugriff auf Copyright oder sonstige Bild-Items ist nicht möglich.

Die Image Toolbar sollte hier auch zur Verfügung stehen, zumindest, um das Copyright anzuzeigen.
Bei Bildern mit Zoom könnte sich aber auch das Detail-Overlay öffnen.

**Comment by sheepyhollow** [comment]
Welche Features brauchen wir realistisch in der Slideshow? Wie ist das z.B. im Quiz - brauchen wir hier auch Tools?
Wie wird dem Frontend mitgeteilt, dass die Image-Tools angezeigt werden sollen? Muss dazu im Backend (Slideshow) eine Option hin?

**Comment by sheepyhollow** [comment]
Im Quiz gibt es mit PR #1056 jetzt auch die Toolbar, wobei nur das Copyright (`attributions`) angezeigt wird. Hier wäre auch Zoom sinnvoll, aber kein Audio, den das Audio "verrät" möglicherweise die Antwort auf die Quizfrage.
Wahrscheinlich müsste `hasAudio` schon beim Input in die solid-core-image Komponente auf `false` gesetzt werden.

**Comment by kerstinhartmann** [comment]
Ich denke die Toolbar der Slideshow sollte eher einfach gestaltet sein. Vielleicht sogar nur Copyright? 
Die Slideshow setzt sich schließlich aus Text und Bild zusammen, wenn wir mehrere Funktionen in einer Toolbar anbieten, verschieben wir den Fokus (wieder) mehr auf das Bild, dabei sollten Text und Bild eher gleichwertig sein. 

Zoom wäre zwar auch hier denkbar, aber ich sehe gerade keinen so großen Mehrwert darin. Auf einem großen Bildschirm erkennt man die  Details der Fotos/Abbildungen gut (sonst könnte vom Erstellenden aber auch ein anderer Ausschnitt gewählt werden) und am mobilen Gerät eigentlich genauso. Also in den momentan existierenden Slideshows ist mir nur eine Liste in AIS/Naturwiss. Analysemeth. Seite 2 aufgefallen, die grenzwertig klein wird mobil, aber noch lesbar find ich. Alle anderen Abbildungen sind auch ohne Zoom stimmig. 
(Ein Detail-Overlay könnte vielleicht sogar eher den Work-/Lernflow unterbrechen, da es den Nutzer etwas aus der Slideshow "rausholt" und separiert das Bild betrachten lässt und dabei ggf. sogar vom eigentlichen Fokus der Slideshow ablenkt, wenn Bilder/Abbildungen etwa nur beispielhaft Objekte zeigen..)
