### ISSUE TITLE
Swagger Parser - Problem bei Array of Objects

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-frontend#1163]
Es scheint so, als könne unser swagger Parser keine Arrays die mit Objekten gefüllt sind parsen (Siehe [Geomat-Steckbriefe](https://geomat-staging.solidelearning.de/profile/tree/101))

Dort werden die Einträge für Kristallsystem(e) und Spaltbarkeit(en) nicht als eigene Kategorieen angezeigt. Swagger zeigt den Type als `"array"` an.

**Comment by chgad** [comment]
Bevor wir den Parser allerdings darauf optimieren ist abzuwartenob wir nicht unsere API Docs ändern.

**Comment by sheepyhollow** [comment]
Hm - ich habe mir das heute mal angeschaut und ich habe noch keine so gute Idee, wie wir diese Verschachtelung lösen. Eigentlich müssten wir ja die Array-Items wieder durch eine Auswertung schleusen, was für ein Typ drin steckt, das kann ja (theoretisch) ewig rekursiv weitergehen.

Was ist mit Änderung der API Docs gemeint?

**Comment by chgad** [comment]
Mir ist, bei Arbeiten an Geomat aufgefallen, dass die 3rd party library die wir nutzen langsam mehr Probleme macht als sie löst. Deshlab ziehe ich einen Wechsel in Betracht. Ein möglicher Kandidat ist [drf-spectacular](https://github.com/tfranzel/drf-spectacular).

**Comment by chgad** [comment]
Das Problem sollte sich lösen wenn man bei dem Type `array` das property `items` inspiziert.

Im Fall von den Kristallsystem(e) und Spaltbarkeit(en) ist dort der Key `refs` hinterlegt der zu einem anderen Serializer also Obkejt führt welches in dem `array`mehrfach auftauchen kann.

**Comment by sheepyhollow** [comment]
Uns ist aufgefallen, dass gar nicht klar ist, ob `CrystalSystems` und `Cleavage` Kategorien sein müssen. Als der GeoMat-Steckbrief (inhaltlich) gebaut wurde, gab es noch gar keine Kategorien/Subrubriken im heutigen Sinn. 

Die finale Form des GeoMat-Steckbriefs muss erst festgelegt werden (@kerstinhartmann @TheGreatDodo &rarr; @chgad), dann sehen wir weiter. 

(meine Lösungsvorschläge gingen übrigens in die falsche Richtung, ich war mit meinem Code-Verweis oben an der falschen Stelle)

**Comment by chgad** [comment]
Mja... wie gesagt 

> Deshlab ziehe ich einen Wechsel in Betracht. Ein möglicher Kandidat ist drf-spectacular.

habe ich [hier](https://github.com/zentrumnawi/geomat-backend/tree/api-docs-refactor) schon auf drf-spectacular gewechselt.

weshalb es wichtig wäre gegen den neuen Endpoint zu testen. (Prinzipiel gleiches Format, endpoint heißt anders.)

**Comment by anhnguyen-98** [comment]
@sheepyhollow Ich bin jetzt dran arbeiten. Aber ich weiß noch nicht woran ich arbeiten sollte und wie ich damit anfangen könnte. Kannst du mal ein bisschen erklären?

**Comment by sheepyhollow** [comment]
Wahrscheinlich ist es besser, wenn @chgad nochmal was dazu sagt. Aber was ich davon verstanden habe:

Aktuell fragen wir den Endpoint `.../swagger/?format=openapi` an, um den Aufbau von `profiles` zu bekommen
https://github.com/zentrumnawi/solid-frontend/blob/f9bbc3ac63d57f4db72d2fd0e05f46f88c9da64e/libs/solid/profile/src/lib/services/profile-definition.service.ts#L30

Christian will auf `.../api/schema` wechseln, weil das besser unterstützt wird.

Unser `profile-definition-service `kann aber die response von `/api/schema` noch nicht verarbeiten - wenn man einfach den Endpoint ändert, funktioniert es nicht. Das Response Object sieht auch etwas anders aus, d.h. die Daten stehen an einer anderen Stelle (siehe [Slack-Post](https://st3elearning.slack.com/files/U1EEYDV9N/F02N7AA0X9V/image.png)).

Ich vermute, dass wir an Stelle des `swagger-schema-official` (siehe [definition service](https://github.com/zentrumnawi/solid-frontend/blob/f9bbc3ac63d57f4db72d2fd0e05f46f88c9da64e/libs/solid/profile/src/lib/services/profile-definition.service.ts#L4)) eine andere dependency brauchen.

**Comment by chgad** [comment]
Also das Problem ist in geomat in der Hinsicht behoben, dass wir die Struktur geändert haben.

Nichts destotrotz ist folgender Sachverhalt dafür verantwortlich:

Die "Unterkategeorien" aka Accordeons stellen eine Tabellenverbindung "Steckbrief --> AndereTabelle" dar.
Bis jetzt, bzw. bis wir es bei Geomat anders gelöst haben, hatten wir eine OneToOne Relation weshalb in den API Docs immer soetwas wie 

    {  ...
      andereTabelle: {
        $ref: "#/definitions/AndereTabelle"
        },
    }

stand.

Bilden wir aber eine OneToMany (Ein Steckbrief besitzt mehrere Verbindungen zu einer Tabelle) wie im Beispiel der Kristallsysteme wird aus obigen Docs etwas wie wir es schon bei den MediaObjects haben :

    {  ...
      andereTabelle: {
        type: "array",
        items: {
          $ref: "#/definitions/AndereTabelle"
        },
        },
    }

Aus technischer sicht fehlt hier also die Evaluierung des `items` key falls ` type === "array"`.


Natürlich muss man dann im Steckbrief schauen wie man das darstellt.

**Comment by chgad** [comment]
> Christian will auf .../api/schema wechseln, weil das besser unterstützt wird.

> Unser profile-definition-service kann aber die response von /api/schema noch nicht verarbeiten - wenn man einfach den Endpoint ändert, funktioniert es nicht. Das Response Object sieht auch etwas anders aus, d.h. die Daten stehen an einer anderen Stelle (siehe Slack-Post).
> 
> Ich vermute, dass wir an Stelle des swagger-schema-official (siehe definition service) eine andere dependency brauchen.

Ja, bis jetzt war es Openapi 2.0 bzw. die swagger Version dieses Standarts.

DRF-Spectacluar implementiert OpenApi 3.0. Bei der Versioniereung ist garantiert dass 2.0 Code nicht mit 3.0 funktioniert.

**Comment by sheepyhollow** [comment]
> Aus technischer sicht fehlt hier also die Evaluierung des items key falls type === "array".

Dagegen kann nicht argumentiert werden:

https://github.com/zentrumnawi/solid-frontend/blob/f9bbc3ac63d57f4db72d2fd0e05f46f88c9da64e/libs/solid/profile/src/lib/services/profile-definition.service.ts#L105

D.h. die Aufgabe ist hier, eine Implementierung zu finden für diesen Fall.

**Comment by sheepyhollow** [comment]
Der Übersicht halber geteilt in neue Issues: 
OpenApi: #1385 
Type Array: #1386
