### ISSUE TITLE
*image-components umbenennen (media object)

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1166]
Im Moment ist `<solid-core-image-...>` die Basis für die Darstellung in den Steckbriefen.

Im Code wäre es besser lesbar, wenn alle Komponenten, die media-objects enthalten, auch einen passenden Namen haben. Also keine Änderung der Funktion, sondern nur eine Umbenennung für mehr Transparenz im Code.

 `<solid-core-image>` &rarr; `<solid-core-media>`
 `<solid-core-image-detail>` &rarr; `<solid-core-media-detail>`
`<solid-core-image-toolbar>` &rarr; `<solid-core-media-toolbar>`

 (der Name `<solid-core-image-dialog> kann bleiben weil der Dialog nur für Bilder gebraucht wird)

Habe ich etwas vergessen?

Diese Umbenennung können wir auch erst dann machen, wenn das media-object fertig ist.

**Comment by anhnguyen-98** [comment]
closed via #1158
