### ISSUE TITLE
Audio Icon

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1168]
Als "Bild" zum Media-Object/Audio soll ein SVG-Icon angezeigt werden mit dem `title` im SVG.

Es gibt verschiedene Möglichkeiten, das zu erreichen:

* https://angular.io/guide/svg-in-templates 
* https://www.chrisjmendez.com/2017/06/17/angular-dynamically-inserting-svg-into-an-element/

Ich denke, die erste Variante ist gut, sie wirkt nur so "groß" - aber es wäre sehr transparent und pure Angular.

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/131356615-99293be5-20a0-44da-b06e-8c417323f64b.png)

**Comment by sheepyhollow** [comment]
Gelöst in 9ebf0dfbd63d14c38287d6ef47c7c66625392b1f

Es fehlt noch: Styling (zentriert, kleiner)

**Comment by anhnguyen-98** [comment]
closed via #1158
