### ISSUE TITLE
Audio description text

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1169]
Im Moment wird der audio-description-text als Overlay angezeigt wie in #1127 ursprünglich gewünscht.

Nach Besprechung mit dem PLANTY-Team würden wir aber gerne den ganzen Bildschirm nutzen, weil der Text sehr lang sein kann.

Vorschlag:

* Audio-Element öffnen &rarr; Audio-Toolbar oben, Audio-Icon ( siehe #1168 ) darunter.
* Beim Klick auf den FAB mit Text-Icon (z.B. `mdiTextBox`) erscheint der Text scrollbar unter der Audio-Toolbar
* Der FAB ist ein Toggle-Button, d.h. er wechselt zwischen Text oder Audio-Icon

![image](https://user-images.githubusercontent.com/13869236/131358888-491d137c-f5e3-42cd-ab0c-01a757223956.png)

**Comment by anhnguyen-98** [comment]
closed via #1158
