### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1171]
Wir sollten bald die Angular Version upgraden.

Dies geht nicht über die Dependencies, sondern muss in einem eigenen Branch durchgeführt werden.

Anleitung hier: https://update.angular.io/?l=2&v=11.0-12.0

**Comment by sheepyhollow** [comment]
Nachdem die aktuellen Aufgaben - vor allem das Media Object - abgeshclossen sind.

**Comment by sheepyhollow** [comment]
Auf den Menü-Kacheln (Landing Page und Slideshow) fehlt nach dem update der Umbruch nach den Bildern

![image](https://user-images.githubusercontent.com/13869236/139704280-9ffb4b35-2041-43a3-8ae1-1fafb78e4026.png)

**Comment by sheepyhollow** [comment]
Sonst habe ich keine Probleme entdeckt, alle Funktionen scheinen zu gehen.
Nur weiß ich nicht, wie sich die neue Slideshow nach dem Update verhält.

[Hier](https://www.questechie.com/2021/09/angular-13-update-whats-new-and-final-release.html) wird allerdings empfohlen, zuerst auf Version 12 zu updaten. Ich weiß nicht, was besser ist....

Wenn Angular 13 Mitte November released wird, können wir das Update auf 13 vielleicht für Januar planen?

**Comment by sheepyhollow** [comment]
Mit #1282 haben wir einen funktionierenden PR mit Updates. 
Es bleibt aber noch einiges aufzuräumen - z.B. tritt das Problem mit den Umbrüchen im landing menu wieder auf (https://github.com/zentrumnawi/solid-frontend/issues/1171#issuecomment-956373964)

Bitte nochmal durch die linter warnings gehen (`nx lint`) und nachsehen, was davon noch gelöst werden kann.

Z.B. solche Sachen (was ist das?)

https://github.com/zentrumnawi/solid-frontend/blob/4905f8d98d9abe13bbbe7d1ce945eca6e4971a97/libs/solid/profile/src/lib/state/profile.state.ts#L22-L29

**Comment by sheepyhollow** [comment]
Das können wir schließen @anhnguyen-98 ?

**Comment by anhnguyen-98** [comment]
closed in [9ab395a](https://github.com/zentrumnawi/solid-frontend/commit/9ab395a465d11ce6a5f3f220ab38926c45be0f6d)
