### ISSUE TITLE
Audio Button Position

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1237]
Der Button sollte nach links etwas mehr Abstand haben (media-dialog)

![image](https://user-images.githubusercontent.com/13869236/138065090-86e17940-0cba-4a44-a6e7-600a1a5c686a.png)

Können wir eigentlich nicht sogar die Audio-Toolbar auch im Media-Dialog einsetzen? Das ist doch eine schöne Lösung jetzt, z.B. immer unten am Rand?

**Comment by sheepyhollow** [comment]
Was denkst Du dazu, die Audio-Toolbar zu verwenden?

**Comment by anhnguyen-98** [comment]
Ich weiß nicht ob die Audio-Toolbar hier passt oder nicht. Vllt. kannst du einen Mock-up erstellen damit wir sehen ob es passt.

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/147677708-b305f1f8-c1ce-4b01-b3fc-c06e761da90c.png)

Ich könnte mir das so vorstellen. Das sieht auf kleinen Bildschirmen gut aus.

**Comment by anhnguyen-98** [comment]
Ja es wäre auch eine gute Idee. Aber wie sollte das aussehen auf großen Bildschirm?

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/147681757-5df4c04d-8bec-4507-95e9-375c012023ae.png)

Wäre das so möglich? Toolbar floating mit abgerundeten Ecken.
