### ISSUE TITLE
`Escape` lässt Menü vollständig verschwinden

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1265]
In der Desktopansicht verschwindet das Menü wenn die `escape`-Taste gedrückt wird.
Es erscheint nicht wieder und es ist keine Navigation mehr möglich.

Wenn die Bildschirmgröße verkleinert und wiederhergestellt wird, erscheint das Menü wieder.

**Comment by sheepyhollow** [comment]
Der Bug ist wahrscheinlich sehr alt und existiert schon in Dive - das ist uns bislang nur nie aufgefallen.
Die Funktion der Escape-Taste im Menü ist wahrscheinlich Material Standard (hier wird `mat-sidenav` verwendet).

Vielleicht ist hier die Lösung? https://material.angular.io/components/sidenav/overview#disabling-automatic-close

**Comment by anhnguyen-98** [comment]
@sheepyhollow D.h einfach die Escape Funktion mit dem automatischen Close deaktivieren oder?

**Comment by sheepyhollow** [comment]
Ja - wenn es sonst keine side-effects gibt...
