### ISSUE TITLE
Dialog bei Klick auf Bild

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1272]
Wäre es nicht sinnvoll, den Media-Dialog direkt beim Klick auf das Bild aufzurufen?
Haben wir da noch nie dran gedacht?

Wir müssten das natürlich von swipe (#966) unterscheiden. Aber wäre das nicht sinnvoll?

**Comment by sheepyhollow** [comment]
@kerstinhartmann

**Comment by kerstinhartmann** [comment]
Ja, das fänd ich auch sinnvoll. 
ggf. bei Doppelklick auf das Bild?

**Comment by sheepyhollow** [comment]
nah, Doppelklick ist für Touch-Geräte unüblich bzw. nicht intuitiv.
Einfach click/tap sollte genügen - wenn es mit swipe keine Probleme gibt. Aber eigentlich müsste beides unterscheidbar gehen.
