### ISSUE TITLE
Images in Messages

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1308]
Die Endpoints liefern ein Image-Objekt das Message angezeigt werden, wenn es existiert.

- Es soll immer nur die `thumbnail`-Variante gezeigt werden.
- das Bild soll links oben angezeigt werden (left floating)
- es soll nur das Bild angezeigt werden, keine Toolbar etc.

**Comment by anhnguyen-98** [comment]
@sheepyhollow kannst du konkreter beschreiben wo das Bild, wo die Texte sein sollte. Falls möglich wäre ein Mock-up super um vorzustellen.

**Comment by anhnguyen-98** [comment]
Oder sieht es ungefähr wie jetzt bei Planty aus, die Positionen, aber mach mal es ein bisschen schicker?

**Comment by sheepyhollow** [comment]
Ja, ungefähr wie in Planty, aber ich mache noch ein Mock-up!

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/147680622-05b61e78-a0a0-4292-b8d9-cdaa115bd9bb.png)

So würden wir das vorschlagen.

**Comment by sheepyhollow** [comment]
Wenn dann noch jemand eine Überschrift mit Markdown machen will, würde das z.B. so aussehen:

![image](https://user-images.githubusercontent.com/13869236/147680863-fb6b7ac4-410e-4686-9906-367bff13b5f8.png)

Das Bild bleibt aber immer links oben mit entsprechenden Margins zum Text.
