### ISSUE TITLE
Bilder-Navigation im Media-Dialog

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1320]
Es sollte möglich sein, im Media-Dialog zwischen den Bildern eines Steckbriefs zu wechseln.

Dazu könnten z.B. Buttons < > über dem Bild erscheinen.

**Comment by sheepyhollow** [comment]
Hatten wir das nicht schonmal diskutiert?

Würde auch zu #1272 passen.

**Comment by kerstinhartmann** [comment]
Wir hatten mal < > Buttons neben den Thumbnails und haben dann entschieden, dass sie eigentlich überflüssig sind, da es ja die klickbaren Thumbnails gibt.

**Comment by kerstinhartmann** [comment]
< >Buttons finde ich gut.
ggf. auch Navigation über Pfeiltasten?

**Comment by sheepyhollow** [comment]
Ja - vielleicht beides, wenn das möglich ist.
Navigation mit Pfeiltasten gibt es schon in der Slideshow, vielleicht können wir das genauso machen.

Bei den Buttons habe ich an sowas wie lightbox gedacht - oder ist das zu fett?

![image](https://user-images.githubusercontent.com/13869236/147693931-d1070e1e-9d2b-4bdb-b6ca-bfa9cc150123.png)

**Comment by sheepyhollow** [comment]
Alternativ auch nur die Pfeile, was aber je nach Farbe des Bildes schwierig sein kann.
Oder wir verwenden einen CSS-Filter (invert, grayscale...), damit der Pfeil immer sichtbar ist.

**Comment by anhnguyen-98** [comment]
closed this in 8b50f23
