### ISSUE TITLE
Audiodateien zu Fotos nicht abspielbar/Bsp. GeoMat

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#1354]
Die Audiodateien, die einzelnen Fotos zugeordnet sind und im Media Dialog abspielbar sein müssten, können zur Zeit nicht abgespielt werden. Der Audiotext wird angezeigt, allerdings gibt es keinen Playbutton/keine Möglichkeit zum Abspielen der Audios.
Woran liegt das? 

_Beispiel "Achat" in GeoMat_

**Comment by sheepyhollow** [comment]
Ich kann im Moment nicht sagen, warum es nicht geht, da wir im Staging wegen eines Fehlers im Update nicht testen können. Sobald dieser Fehler behoben ist, sollten wir auch wieder Audio haben, in der Update-Version funktioniert es - zumindest lokal.

Vielleicht können wir auch gleich die Idee in #1237 umsetzen.

**Comment by anhnguyen-98** [comment]
Mir ist eingefallen, dass das Problem nicht an dem Frontend liegt, sondern an dem Backend. Beispielweise bei _"Achat" in GeoMat_ kann das Frontend die Audio-Quellen nicht laden, deswegen ist das Audio nicht abspielbar.
[https://cdn.geomat.uni-frankfurt.de/staging/32_Achat.mp3](url) (sehe hier)

**Comment by sheepyhollow** [comment]
Aber https://cdn.geomat.uni-frankfurt.de/production/audio/32_Achat.mp3 ist korrekt und wird bei mir auch abgespielt, wenn ich die URL im Browser lade. Und wenn das Audio nicht geladen werden kann, sollte doch wenigstens der play-button erscheinen.
