### ISSUE TITLE
Glossar in Menüauswahl hinzufügen

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#1360]
Das Glossar soll als eigenständige Zeile links in der Menüansicht hinzugefügt werden. 
Beim Anklicken dieser Zeile soll das Glossar so ausklappen, wie es momentan der Fall ist, wenn das Glossar-Icon geklickt wird. 

Mein Vorschlag für die Sortierung des Menüs wäre standardmäßig die Anzeige der Glossar-Zeile als letzte Content-Funktion, also vor Info, Datenschutz und Kontakt.

**Comment by anhnguyen-98** [comment]
closed this in f65e51c
