### ISSUE TITLE
Guided tour

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1366]
Wir sollten in s.o.l.i.d. eine "Tour"-Funktion haben, mit der die wichtigsten Features der App erklärt werden.

Mir fallen hierzu zwei Lösungen ein:

1. Eine Slideshow mit Erklärungen
  - Vorteil: Wir müssen nichts neu programmieren - die Slideshow wäre aber immer zu sehen 

2. Eine "interaktive" Tour mit Overlays, die beim ersten Start (per flag im localstorage) angezeigt wird und die Funktionen erklärt.

Was ist Deine Meinung zu 2 @anhnguyen-98 ? Kannst Du einschätzen, wie viel Aufwand das ist?

Es gibt Tools, die das können, z.B. https://lsqlabs.github.io/ngx-guided-tour

**Comment by anhnguyen-98** [comment]
Die 2 wäre sehr cool. Wie viel Aufwand kann ich noch nicht einschätzen. Es kommt drauf an, ob wir nur die Tour auf die Landing-Page durchführen würden oder auch die in anderen Seiten wie Profiles oder Slideshow. Wenn alles betrachtet werden, ist es echt viel Aufwand.

**Comment by sheepyhollow** [comment]
Genügt es für die Landing Page @kerstinhartmann?
Ansonsten würde es genügen bei landing page, slideshow (nicht *select) und profile, das wären dann nur drei Komponenten. Quiz ist eigentlich selbsterklärend...

**Comment by kerstinhartmann** [comment]
Ich denke auf der Landing Page reicht - Wenn wir dort auf die einzelnen Funktionen hinweisen, ist es ja kein so großer Schritt mehr die Funktionen auch auszutesten als User. Es wir aber eben auch keine Funktion "übersehen".

**Comment by sheepyhollow** [comment]
Das können wir doch schließen, @lthuong ?
