### ISSUE TITLE
Base Profile Toolbar glitch

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1375]
Das hier habe ich eben gesehen bei < 600px

![image](https://user-images.githubusercontent.com/13869236/151457066-7f7aca90-a409-4960-aeba-8cfda5f993e4.png)

![image](https://user-images.githubusercontent.com/13869236/151457007-6455c208-ba85-41b5-9f61-e7dd82e51b1e.png)

Über die Höhe der Toolbar müssen wir aber ohnehin mal nachdenken. Wir wurden schon einige Male gefragt, warum die Menu-Entries und die Toolbar nicht die gleiche Höhe haben:

![image](https://user-images.githubusercontent.com/13869236/151457313-4887c43f-0e14-4ea8-9821-08198830e882.png)

**Comment by anhnguyen-98** [comment]
@sheepyhollow dazu wollte dich auch fragen, ob was hier erwünscht ist. Ob die beiden haben die gleiche Höhe wie Toolbar (also 64px) oder wie Menu-Entries (48px). Wenn es 48px klein ist, haben wir bei `Dive` noch `trivial_name` bei der Profile-Titel, also nicht genug Raum umzuzeigen. Bei dem Löschen des Titel-Formatters bräuchte ich hier eine Rückmeldung von dir

**Comment by anhnguyen-98** [comment]
![Screenshot 2022-03-24 at 13 22 41](https://user-images.githubusercontent.com/71195698/159915325-9f65d11c-a8df-416c-b62d-4e40169ff706.png)

So ist es wenn man 48px wie Menu-Entries stellt.

**Comment by anhnguyen-98** [comment]
64px ist zu groß und macht dem Menü hässlich. 56px find ich für die beiden super wenn es ist erwünscht, dass die beiden die gleiche Höhe haben würden.

**Comment by sheepyhollow** [comment]
Zuerst mal: Hast Du #1401 gesehen? Das steht ja zueinander in Beziehung.

Der Zeilenabstand zwischen `name`/`title `und `trivial_name` könnte evtl. noch etwas kleiner sein, aber ja - 48px ist einfach zu eng.

Ansonsten: Wenn es mit 56px passt, dann ist das ein guter Kompromiss!

**Comment by anhnguyen-98** [comment]
Ja das komplett im Bezug auf #1401 würde ich als nächstes machen. Ich wollte da nur die Höhen bestimmen, weil die Toolbar den Titel beinhaltet.

**Comment by sheepyhollow** [comment]
ja, gut! Danke 🙂 


Und von wegen nächste Aufgabe, dazu schreibe ich in Slack nochmal.

**Comment by sheepyhollow** [comment]
Längst erledigt!
