### ISSUE TITLE
Quiz: Range component

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1387]
Implement a new quiz component **Range** (type code `RN`)

It should

* display a question text (+ image/mediaObject)
* Display a range slider with respective labels 
* allow the user to set the slider thumb
* Display the respective feedback after hitting the standard button "Lösungen anzeigen"
* Display the allowed tolerance on the slider bar (some CSS magic needed)

You can basically follow the instructions in #708 and #744 for the quiz component.
See also the respective backend issue https://github.com/zentrumnawi/solid-backend/issues/134

When the component is finalized, the data model should deliver
* the question text and optional media objects
* correct value (number)
* range maximum (number)
* range minimum (number)
* [step size (number)]
* tolerance (number)
* feedback_correct (string)
* feedback_false (string)

The component's logic part should check if the user input (= slider position) is within the given _tolerance_ which will be given as one number and interpreted as +/-. If the tolerance is 0 (or `null`), the user must hit the exact value.

**Comment by sheepyhollow** [comment]
We still need to discuss if `step size` will be given as a variable or if we apply some general logic to make it reasonable.

There are some object properties (e.g. Mohs scale of mineral hardness which is discrete numbers) where a non-integer wouldn't make sense.

**Comment by sheepyhollow** [comment]
Mir ist außerdem aufgefallen, dass der thumb nur am Anfang angezeigt wird und nicht bei der Auswahl. Am Anfang überdeckt der thumb auch den min-tick. 

Ich würde es gut finden, wenn der thumb immer angezeigt wird. Wenn es klappt, dass der thumb bei 100% auch den max-tick überdeckt, dann brauchen wir oben die styling-Regeln nicht, dann kann der max-tick immer lightgray sein.

**Comment by lthuong** [comment]
Entschuldigung für die späte Rückmeldung 🥲

> Ich würde es gut finden, wenn der thumb immer angezeigt wird. Wenn es klappt, dass der thumb bei 100% auch den max-tick überdeckt, dann brauchen wir oben die styling-Regeln nicht, dann kann der max-tick immer lightgray sein.

Ich habe es vorher schon versucht, der Thumb immer zu zeigen und es hat gut funktioniert. D.h was ich machen soll ist:

1.  Der Thumb immer zeigen lassen
2.  Min- und max-tick: lightgray (wenn der Thumb bewegt wird)
3.  Min: quiz-incorrect/correct (nach Auswertung) 

Oder ?

**Comment by sheepyhollow** [comment]
fast ;-) 

min-tick und max-tick sollen die gleiche Farbe _wie der angrenzende Track_ haben, so dass sie optisch Teil des Tracks sind:

![image](https://user-images.githubusercontent.com/13869236/172812824-40f7e77b-4b51-4467-a5fb-871d2d4df4b1.png)

Verständlich so?

**Comment by sheepyhollow** [comment]
Eigentlich kann der max-tick immer grau sein - bei 100% wird er sowieso vom Thumb überdeckt (oder?)
