### ISSUE TITLE
Quiz component overhaul

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1388]
In Zukunft soll das Quiz nicht mehr vollständig vom Backend geliefert werden.

* Es wird einen quiz-Endpoint geben, der Metadaten liefert (Gesamtzahl der Fragen, vorhandene Tags, mögliche Schwierigkeit)
  * Name des Endpoints ist `/quizmeta` 
* Quiz-Parameter werden im Frontend gewählt und per Request an das Backend geschickt 
  * `/quizsession?count=<nr-of-questions>&tags=<tag-1>,<tag-2>,...&difficulty=1,2,...`
* Die Response ist ein definiertes Quiz-Paket, das den ausgewählten Parametern entspricht.

Siehe auch das backend-issue: https://github.com/zentrumnawi/solid-backend/issues/138

Das heißt, es müssen zwei API-Calls gemacht werden.

Die Quiz-Start-Komponente muss dann erweitert werden:

* [Custom Text je nach App (siehe auch #1063)]
* insgesamt besseres Styling je nach Bildschirmgröße (?) (Siehe auch  #1401)
* Start-Button größer und im App color scheme (wie "Lösungen anzeigen"-Button)
* keine Auswahl der Fragenanzahl, sondern einen Defaultwert (z.B. 10 Fragen)

_Zusätzlich_ gibt es ein Expansion Panel, in dem die Quizparameter ausgewählt werden können
* Anzahl der Fragen (Number oder Slider?)
* Tags (Chips?)
* Difficulty (Slider?)

Umgang mit der response:

* wenn `response.length === 0` ist (also keine Fragen mit der Parameterkombination gefunden werden) wird eine Fehlermeldung angezeigt "Ooops in dieser Kombination gibt es keine Fragen, versuche eine andere Kombination." (oder so)
* wenn `response.length < <gewünschte Anzahl>` wird eine Meldung ausgegeben "Ooops in dieser Kombination gibt es keine Fragen, versuche eine andere Kombination." (oder so)
 
Die Quiz-Ende-Komponente soll auch noch erweitert werden, dass ist aber ein eigenes Issue.

**Comment by chgad** [comment]
> wenn response.length < <gewünschte Anzahl> wird eine Meldung ausgegeben "Ooops in dieser Kombination gibt es keine Fragen, versuche eine andere Kombination." (oder so)

Ich würde den User einfach die Quizsession machen lassen. Sprich Nachricht, dass wir nicht soviele Fragen in der Kombination haben, aber die, die wir haben bearbiten lassen.
