### ISSUE TITLE
Feedback-Form Bug

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1393]
Nach einem Update tritt manchmal ein Fehler im Feedback Formular auf, dann fehlt das Padding:

![image001](https://user-images.githubusercontent.com/13869236/153375926-200ff3ae-98a6-4c97-8bd5-741a6cea4baa.jpg)

Nach einem Reload tritt der Fehler nicht mehr auf.

**EDIT:** Der Bug passiert auch, wenn zuerst der Media-Dialog und dann direkt der Feedback-Dialog aufgerufen werden (siehe #1420)

**Comment by sheepyhollow** [comment]
Das war schon bekannt - ist das nicht eigentlich schon gelöst?
Es ist beim Planty-Release (s.o.l.i.d.-Version 2.5.0) wieder aufgetreten.

**Comment by sheepyhollow** [comment]
Vielleicht muss in der scss-class `mat-dialog-container` explizit `padding: 24px` gesetzt werden?

**Comment by lthuong** [comment]
Bei mir tritt der Fehler nicht auf. Also ich habe das Dialog schon untersucht und kann sehen, dass `padding: 24px` schon da ist

**Comment by lthuong** [comment]
Wenn ich `padding : 0` in [media-dialog.component.scss](https://github.com/zentrumnawi/solid-frontend/blob/dev/libs/solid/core/src/lib/components/media-dialog/media-dialog.component.scss) weglasse, tritt das Problem nicht mehr auf

```
::ng-deep {
  div.cdk-overlay-container {
    mat-dialog-container {
      overflow: hidden;
      padding: 0;
    }
  }
```

**Comment by sheepyhollow** [comment]
wieso media-dialog? 🤔 Das ist doch eine ganz andere Komponente?

**Comment by sheepyhollow** [comment]
AH - Sorry, ich habe das Issue nicht richtig gelesen... 🙈

`::ng-deep` bricht die style-encapsulation. Wahrscheinlich gilt das dann für alle `mat-dialogs` 

Aber - wenn `padding: 0` hier wegfällt, haben wir ein Padding um den Media-Dialog

![image](https://user-images.githubusercontent.com/13869236/158378664-4173c971-f5c2-4d47-b7ce-222adbe04c3e.png)
vs. 
![image](https://user-images.githubusercontent.com/13869236/158378752-88d9a387-54eb-4f14-abae-e8513b7b5bcc.png)

Müsste nicht andersherum ein explizites `padding: 24px` in den feedback-dialog eingefügt werden?

**Comment by sheepyhollow** [comment]
Okay, das mit der lange angekündigten ng-deep-deprecation ist wohl ein schwieriges Thema (und gehört auch nicht in dieses Issue). Es gibt viele [Diskussionen](https://www.google.com/search?q=ng-deep+deprecation) dazu, vielleicht muss jemand ein bisschen lesen.
 Aber Vorsicht - immer schauen, wie aktuell die Posts sind.

**Comment by lthuong** [comment]
Ich habe schon `padding: 24px` in den feedback-dialog eingefügt, aber das wird am Ende des Tages auch bei `padding: 0` überschrieben

**Comment by lthuong** [comment]
Es funktioniert wenn ich `padding: 24px !important`  in den feedback-dialog einfüge

**Comment by sheepyhollow** [comment]
das ist ein bisschen witzig, weil es bei dem anderen Styling (transparent) nicht gebraucht wird 😁
