### ISSUE TITLE
Report-Button

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1394]
Planty möchte gerne einen zusätzlichen Feedback-Button in der Titelzeile, um inhaltliche Fehler z.B. in Profiles und Slideshows direkt melden zu können (Feedback-Formular). Der Button soll optisch mit der Toolbar verbunden sein und ungefähr so aussehen

![image002](https://user-images.githubusercontent.com/13869236/153376606-13101998-19de-4769-a441-4e089cecb275.png)

- ~der Button soll in Slideshows, Quiz und Profiles erscheinen~
- [x] der Button soll generell in der main toolbar sein (in jeder Komponente)
- [x] Der Button öffnet das Feedback-Form
- [x] Das Icon ist noch nicht final, zuerst mal das Feedback-Icon benutzen und später austauschen
- [x] Styling anpassen 
- [x] Report-Button in solid-core-config konfigurierbar machen (default: aktiv)
- [x] Das (optionale) Logo soll links vor dem Schriftzug sein
  - [x] b1e2c47e8e02afa2c508e318205a687079e69944 muss zurückgebaut werden (Viktoria sagt "sorry!")
  - [x] es gibt dann nur noch _ein_ (optionales) `appLogo` vor dem `appName`
  - [x] `solid-core-config.ts` im core-Modul und in planty anpassen (wird nur dort benutzt - Tipp: [Suche benutzen](https://github.com/zentrumnawi/solid-frontend/search?q=appLogoLarge+appLogoSmall))

Die anderen Aufgaben machen wir in ein eigenes Issue &rarr; #1404

**Comment by lthuong** [comment]
Ich schaue die Aufgabe erstmal an und ich hoffe, dass ich die lösen kann :)

**Comment by sheepyhollow** [comment]
A few thoughts:

* der Button muss vermutlich in der skeleton component ins [base-layout](https://github.com/zentrumnawi/solid-frontend/blob/dev/libs/solid/skeleton/src/lib/components/base-layout/base-layout.component.html)
  * die Verbindung zur Toolbar von slideshows und profiles ist nur ein optischer Trick; der Button "lebt" in der app main toolbar
* In der `mat-toolbar` ist auch das Logo, das ist also straightforward
* wie das Feedback angezeigt wird kannst Du Dir in der `landing`-component oder im `main-menu` anschauen.
* das base-layout weiß aber nicht, welche Komponente gerade angezeigt wird, dafür müsste eine Lösung gefunden werden (da habe ich aber auch keine Ahnung...)

**Comment by sheepyhollow** [comment]
Ich habe das oben als Aufgabe hinzugefügt. Ich denke, das ist möglich, aber nicht ganz einfach.
Vielleicht können wir einen "Fehlercode" mit anhängen, der irgendwie fancy aussieht, aber nur die IDs enthält.

**Comment by sheepyhollow** [comment]
Richtig - damit kannst Du anfangen.

Wenn das funktioniert gibt es noch einige Details und Verfeinerungen.

**Comment by sheepyhollow** [comment]
Kleine Klarstellung, wir haben jetzt entschieden, dass der Button _immer_ zu sehen sein soll, unabhängig von der Komponente.
Damit wird es deutlich einfacher.

Es bleibt aber die Idee, dem FeedbackService die Information mitzugeben, in welcher Komponente und auf welcher Seite/Quizfrage etc. wir gerade sind.

**Comment by lthuong** [comment]
Ich habe einen Button schon erstellt, der nach einem Klicken das Feedback-Form zeigt. Es bleibt aber eine Frage, die ich noch nicht so klar verstehe: Also welche Informationen sollen wir dem FeedbackService mitgeben ? Ich habe eine Idee, dass die Informationen von dem <kbd>main-menu</kbd> zu dem <kbd>base-layout</kbd> übermittelt werden sollen. Und dann "erhält" das FeedbackService diesen Informationen nach einem Klicken

**Comment by sheepyhollow** [comment]
Mir ist - vielleicht - ein "Shortcut" eingefallen.
Eigentlich sind alle Informationen, die wir brauchen, im _Router_ verfügbar (Stichwort: `ActivatedRoute`).

Das Feedback-Form hat keine eigene Route, da es ein Dialog ist. d.h. wenn wir in der Feedback-Komponente mit `ActivatedRoute` die aktuelle Route (= die aktuelle URL) auslesen, dann wissen wir, wo der User gerade ist und von wo das Feedback aufgerufen wurde.

Dann können wir auch die Route (bzw. url) im Feedback mitsenden (z.B. an den Text anhängen). Das könntest Du mal probieren.

Ein Nachteil: Wir können nicht entdecken, ob ein Feedback aus dem Glossary kommt. Dazu müssten wir wissen, herausfinden, ob das Glossar im Moment ausgeklappt ist (das Glossar hat auch keine eigene Route).

**Comment by sheepyhollow** [comment]
Du kannst Dir z.B. in `tree.component.ts` anschauen, wie die `ActivatedRoute` eingebunden wird.

Aber wir können aktuell auch nicht unterscheiden, _wie_ der `FeedbackService` aufgerufen wurde: Vom neuen Button, aus dem `main-menu` oder aus `landing`. `

Was können wir hier tun? Könnten wird den `FeedbackService` erweitern und eine Art "caller-id" mitsenden?

**Comment by sheepyhollow** [comment]
(btw. wenn Du eine funktionierende Änderung hast, dann kannst Du auch schon einen PR machen und pushen, dann können wir das anschauen 😉 - transparency is king!)

**Comment by sheepyhollow** [comment]
Ich sehe gerade, dass in der `base-laout.component.ts` ja auch `Glossary` gesteuert wird. Damit sollte es eigentlich einfach sein, herauszufinden, ob das Glossary offen ist (und ob das Feedback aus dem Glossary kommt).

**Comment by sheepyhollow** [comment]
eine Styling-Idee, die ich etwas besser finde. @kerstinhartmann ?
![image](https://user-images.githubusercontent.com/13869236/154464122-6da6fade-5a32-405c-9e17-3d77907d2e3c.png)

**Comment by sheepyhollow** [comment]
@lthuong Ich habe jetzt mal eine Checkliste für die einzelnen Punkte des Issues eingefügt. Dann ist leichter zu sehen, was noch getan werden muss und was schon erledigt ist.

**Comment by kerstinhartmann** [comment]
Hattest du die Outlined-Idee von Viktoria auch nochmal ausprobiert? Dann wäre das Ausrufezeichen ggf. besser zu erkennen oder?

**Comment by sheepyhollow** [comment]
Das ist ja nur das Icon - das ersetzen wir dann. Mir ging es hier nur um die "Lasche"

**Comment by kerstinhartmann** [comment]
Achso - die Lasche ist hiermit offiziell genehmigt. :D

**Comment by sheepyhollow** [comment]
@lthuong - Kannst Du bitte zwei Sachen noch machen:
- Styling des Report-Dialogs (rote outline um den gesamten Dialog)
- der report-Button sollte in solid-core-config für jede App aktiviert oder deaktiviert werden können:
  - `libs\solid\core\src\lib\solid-core-config.ts` muss um eine Eigenschaft (z.B. `error_report`) erweitert werden
  - `<app>\src\app\solid-core-config.ts` muss in allen Apps gesetzt werden (default: `true`)
  - Anzeige des Buttons im base-layout je nach Wert der neuen Eigenschaft (*ngIf)
