### ISSUE TITLE
Intelligentes Feedback 

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1404]
Der in #1394 erstellte Report Button soll ein Feedback mit Parametern öffenen.

- [x] Unterscheidung, ob das Feedback vom neuen Report-Button oder aus dem Menü geöffnet wurde
- [x] "Betreff"  und "Titel" des Feedback-Forms sollen dynamisch sein:
  - bei Aufruf aus dem Menü: Titel = "Kontakt und Feedback", Betreff = "Feedback"
  - Aufruf über Report-Button: Titel = "Fehler melden", Betreff = "Fehlermeldung"
- [x] Eine Information über die aktuelle URL soll an das Feedback angehängt werden (`ActivatedRoute`)
- [x] Sonderfall Glossar: Wenn das Glossar offen ist, soll die Information 'Glossar' an das Feedback angehängt werden.

**Comment by lthuong** [comment]
@sheepyhollow das ist richtig hilfreich. Vielen Dank für deine Mühe !!!

**Comment by kerstinhartmann** [comment]
Das PLANTY-Team hatte noch angeregt auch schon einen Standard-Text einzufügen sowas wie: 

"Liebes Team, Ich habe folgenden Fehler entdeckt: [... User schreibt Text...]
Link: [... automatisch URL einfügen] Liebe Grüße "

Was denkt ihr dazu?

**Comment by lthuong** [comment]
Bisher habe ich noch keine neue Idee. Ich probiere erst erstmal mit dem Standard-Text und später wenn ich mir irgendwas dazu einfallen lassen, sage ich euch Bescheid.
