### ISSUE TITLE
Multi Profiles

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-frontend#1405]
Mit diesem [Issue](https://github.com/zentrumnawi/solid-backend/issues/152) wollen wir mehrere unterschiedliche Steckbriefe ermöglichen.

Das Frontend muss sich dahingegend anpassen, dass die Key's im Response, die für Steckbriefe stehen dann der pattern `"*_related"` folgt.

**Comment by sheepyhollow** [comment]
Ich gehe davon aus, dass hier Anpassungen gemacht werden müssen:

https://github.com/zentrumnawi/solid-frontend/blob/dev/libs/solid/profile/src/lib/services/profile-definition.service.ts

**Comment by sheepyhollow** [comment]
https://solid-backend.uni-frankfurt.de/planty/staging/profiles/

Auf diesem Endpoint sind die multi-profiles umgesetzt.

**Comment by sheepyhollow** [comment]
Das `TreeNodeApi` interface erwartet eine property `profiles`, das die einzelnen Steckbriefe enthält.

Im neuen Endpoint gibt es die property `profiles` nicht mehr, sondern dynamische property names (in Planty: `wine_related` und `plant_related`). Dieser property name folgt immer dem Pattern `*_related` (siehe oben). 

Die in Objekte in diesen properties sind normale Steckbriefe, die unser profile-definition-service verarbeiten kann.

Das Tree-Mapping funktioniert an dieser Stelle nicht mehr:
https://github.com/zentrumnawi/solid-frontend/blob/1cf6f492454276d17d488634aeb902c424f63e9a/libs/solid/profile/src/lib/state/profile.state.ts#L135

**Comment by sheepyhollow** [comment]
Solved in #1876
