### ISSUE TITLE
403 Sentry cals

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-frontend#1410]
Mir ist aufgefallen, dass in allen Frontend instanzen immer wieder POST Requests and unser Sentry raus gehen die mit Status 403 zurückkommen. Was ist da los?

**Comment by sheepyhollow** [comment]
@chgad dieser CORS-Error - liegt das an unserem Request oder am Server?

```
Access to fetch at 'https://sentry.solidelearning.de/api/34/envelope/?sentry_key=6772dbe6a4bb42e88711f20924eefa8e&sentry_version=7' from origin 'https://geomat.uni-frankfurt.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by sheepyhollow** [comment]
Der Fix (`autoSessionTracking: false`) hat das Problem offenbar auf dem Server nicht gelöst.
Investigating...
