### ISSUE TITLE
Report-Button fixes

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1420]
Änderungswünsche am Report-Button Feature (#1400)

- [x] "Fehler gefunden" vor `location` in message (&rarr; [code](https://github.com/zentrumnawi/solid-frontend/blob/c77d84f712a119aab2f20c9de365718f33fa940a/libs/solid/skeleton/src/lib/components/feedback/feedback.component.ts#L49))
- [x] Farbe des Icons in GeoMat, Dive und AIS anpassen (momentan weißes Icon auf weißem Hintergrund)
- [x] #1393 tritt auf, wenn Zoom-Popupfenster genutzt wurde und anschließend Report-Button verwendet wird
- [x] Button bleibt ausgegraut, wenn Report abgebrochen wird
![grafik](https://user-images.githubusercontent.com/66634630/158063289-9c42f9bb-0f29-4ff2-a433-6697d63f242a.png)

**Comment by kerstinhartmann** [comment]
- [ ] Farbe des Icons in GeoMat & Dive anpassen (momentan weißes Icon auf weißem Hintergrund)

**Comment by sheepyhollow** [comment]
Die Farbe muss in der class `.mat-icon` explizit auf "black" gesetzt werden.

**Comment by sheepyhollow** [comment]
Der ausgegraute Button tritt nur bei OnCancelClick auf. 
Es gibt verschiedene Lösungen, wie z.B. ein explizites blur() auf den Button.

Aber das Einfachste ist das hier: https://stackoverflow.com/a/56760618 - das würde ich vorschlagen.

Das muss dann von der FeedbackComponent an das BaseLayout kommuniziert werden.
