### ISSUE TITLE
Guided-tour landing page

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#1451]
- [x] Die Guided-Tour soll nur beim ersten Besuch der Seite angezeigt werden &rarr; Flag in Local Storage
- [x] Die fuided-tour soll zu jedem Zeitpunkt abgebrochen werden können mein Vorschlag wäre: "X" oben rechts, wie bei den Quizfragen.
- [x] Hintergrund soll jeweils ausgegraut sein und Textfelder weiß, die Beschreibungstexte/Inhalte zeigen.
- [x]  Zusätzlich soll es Pfeile geben, die auf die zu beschreibende Funktion hinweisen. Farbe der Pfeile auch weiß? (Probiert hier mal aus, was gut aussieht).
- [x] Pro "Seite" fände ich einen Punkt-Symbol gut, dass sich dann zu einem Haken verändert, wenn die Seite gelesen wurde: So z.B.
![1647357058441](https://user-images.githubusercontent.com/66634630/158409866-189114db-af10-4e88-8d02-17c027239c9e.jpg)

Inhalte der guided Tour: 
1. - [x] Willkommen bei [Titel der App]. In einer kurzen Tour möchten wir dir die wesentlichen Funktionen zeigen.
2. - [x] Über das Menü erreichst du die verschiedenen Funktionen der App.
 **Frage: Automatische Auflistung der inhaltlichen Funktionen (GeoMat z.B. "Steckbriefe" und AIS "Fundstücke")?** 
**Frage: Einzelne Funktionen kurz erläutern oder ist das schon zu viel?**
3. - [x] Über das Listenmenü kannst du zu einer anderen Funktion wechseln oder wieder zurück zur Startseite gelangen. 
4. - [x] Für inhaltliches Feedback haben wir den Fehler-Melden-Button. So kannst du uns schnell und einfach auf inhaltliche Fehler hinweisen. 
5. - [x] Hier findest du unser [AppTitel]-Glossar mit wichtigen Fachbegriffen zum Nachschlagen und Lernen. 
6. - [x] Über das Kontaktformular kannst du uns Feedback geben, uns auf technische Probleme hinweisen oder andere Fragen an unser Team richten.
7. - [x] Wir wünschen dir viel Freude beim Lernen und Entdecken der [TitelderApp]-App.

Ich würde erstmal bei der Du-Ansprache bleiben. Ggf. müsste das aber pro App anpassbar/veränderbar sein - in Planty sollen die Studierenden mit "Sie" angesprochen werden. 

Ergänzung zu 2. Erläuterungen der Kacheln: Ich hoffe eine App-spezifische Lösung ist möglich. 
Hier mein Formulierungsvorschlag: 
- [x] **GeoMat:**
Steckbriefe: Die Steckbriefe zeigen in übersichtlicher Form die wichtigsten Mineraleigenschaften sowie ergänzend Fotos, Videos und/oder Audios.
Selbsttest: Mit dem Selbsttest kannst du deinen bisherigen Kenntnistand prüfen und dein mineralogisches Wissen festigen. 
Slideshows: Hier sind weitere Inhalte dargestellt, die dein Wissen erweitern und vertiefen.
Kristallsysteme: Hier werden die 7 Kristallsysteme als interaktive, dreidimensionale Körper angezeigt.
Info/Datenschutz: Hier findest du allgemeine Informationen zu GeoMat*digital* und dem Projekt s.o.l.i.d. sowie unsere Datenschutzhinweise. 

- [x] **Div-e:** 
Steckbriefe: Die Steckbriefe zeigen in übersichtlicher Form die wichtigsten Pflanzeneigenschaften sowie ergänzend Fotos, Videos und/oder Audios.
Selbsttest: Mit dem Selbsttest kannst du deinen bisherigen Kenntnistand prüfen und dein pflanzenkundliches Wissen festigen.
Merkmale: Hier sind weitere Inhalte dargestellt, die dein Wissen erweitern und vertiefen.
Info/Datenschutz: Hier findest du allgemeine Informationen zu Div-e und dem Projekt s.o.l.i.d. sowie unsere Datenschutzhinweise. 

- [x] **AIS:** 
Keramikwissen: Hier sind archäologische Inhalte dargestellt, die dein Wissen erweitern und vertiefen.
Selbsttest: Mit dem Selbsttest kannst du deinen bisherigen Kenntnistand prüfen und dein archäologisches Wissen festigen.
Fundstücke: Hier findest du in übersichtlicher Form Fundstückbeispiele mit ihren Eigenschaften sowie Fotos, Videos und/oder Audios.
Info/Datenschutz: Hier findest du allgemeine Informationen zu AIS und dem Projekt s.o.l.i.d. sowie unsere Datenschutzhinweise. 

- [x] **PLANTY:** Auch hier tritt wieder die Frage nach der Ansprache auf, ich habs nun entsprechend der Wünsche mit "Sie" formuliert.
Steckbriefe: Die Steckbriefe zeigen in übersichtlicher Form die wichtigsten Rebeneigenschaften sowie Fotos, Videos und/oder Audios.
Selbsttest: Mit dem Selbsttest können Sie Ihren bisherigen Kenntnistand prüfen und Ihr Wissen festigen.
Wissensgalerien: Hier sind weitere Inhalte dargestellt, die Ihr Wissen erweitern und vertiefen.
Info/Datenschutz: Hier finden Sie allgemeine Informationen zu PLANTY2Learn und dem Projekt s.o.l.i.d. sowie unsere Datenschutzhinweise.

**Comment by lthuong** [comment]
Bei dem Menü können die einzelne Funktionen kurz erläutern. Das ist doch machbar

**Comment by sheepyhollow** [comment]
So lange die Box nicht zu groß wird 😉 
@kerstinhartmann - dann brauchen wir wohl noch Texte dazu.

@lthuong Die Komponenten haben in den Apps unterschiedliche Namen. Ist die Guided-Tour eine globale Tour oder können wir sie App-spezifisch einstellen?

**Comment by lthuong** [comment]
Das muss ich kurz ausprobieren. Der Inhalt muss quasi dynamisch sein ne ?

**Comment by sheepyhollow** [comment]
Ja - wir haben die Möglichkeit, Texte oder Textbausteine in `apps/<AppName>/src/assets` zu hinterlegen.
Ich weiß nicht, ob das der beste Weg ist, aber so machen wir das auch mit den Icons.

Das wäre vielleicht auch eine Lösung für die Anrede (Du / Sie) vgl. auch #1063

**Comment by lthuong** [comment]
So habe ich auch gedacht. Also ich baue erstmal die Guide-tour auf und vielleicht später wenn ich irgendwas einfalle, sage ich euch dann Bescheid

**Comment by kerstinhartmann** [comment]
hab die Textvorschläge oben eingefügt

**Comment by sheepyhollow** [comment]
@kerstinhartmann - bestehst Du auf die ✔️ -Buttons? Oder ist der [Standard von IntroJs](https://introjs.com/) (Punkte und ein längerer Strich für den aktuellen Schritt) auch okay?

Und: Wenn man die Tour beendet hat oder abbricht sollte man sie wieder starten können. Wo packen wir diese Funktion hin?

**Comment by kerstinhartmann** [comment]
Nein da bestehe ich nicht drauf. Das war nur ein Vorschlag: Hauptsache man kann den Fortschritt erkennen. 

In den Infobereich? So ganz passend ist es da zwar nicht, aber irgendwie passt die Frage "wie bediene ich die App?" dann doch zu den Inhalten die wir im Infobereich darstellen "Was ist Solid?/was ist [App-Titel]?"

**Comment by sheepyhollow** [comment]
Wir haben keinen "Einstellungen"-Bereich. Und ich sehe das auch in Verbindung zum Thema "landing page" (diese Willkommensnachricht auf der Startseite). Die kann man auch ausblenden und dann wird sie - auf diesem Gerät - nie wieder angezeigt. Die sollte man auch wieder aktivieren können. Das hätte ich jetzt in die "News" verortet, aber vielleicht gibt es da noch andere Ideen?

Es ist auch möglich, vor dem Abbrechen noch eine Info zu zeigen wie "Du kannst die Tour jederzeit neu unter... starten".

**Comment by sheepyhollow** [comment]
Ooookay... @lthuong - Kerstin und ich haben heute nochmal die Tour angeschaut und haben ein paar Änderungsvorschläge - ich hoffe, nicht zu viele 😓 

Die wichtigste Änderung: wir wollen die Funktionen an den Menü-Icons/Tiles (landing-component) erklären, nicht im Main-Menü. Es ist nicht so richtig logisch, dass wir die schönen Grid-Tiles mit Icons haben und nur das Menü erklären. 

Das müsste natürlich App-spezifisch sein, weil die Reihenfolge der Tiles nicht bei allen Apps gleich ist. Das sollte aber über die json-Datei gehen, denn dort ist die Reihenfolge der Steps definiert (oder?)

Dann wäre folgende Reihenfolge richtig:
1. Willkommensnachricht 
2. Menü-Button (mobile) oder gesamtes Menü (fixed) - das haben wir ja schon besprochen
  - das bedeutet, dass das Menü nicht ausgeklappt werden muss. 
4. Landing Page Kacheln/Tiles in der App-spezifischen Reihenfolge
5. Glossar
6. Report Button
7. evtl. noch Profiles
Finish

Können wir das so machen? Soll das oben im Issue neu geordnet werden?

**Comment by sheepyhollow** [comment]
Und noch ein Vorschlag: Wollen wir die Step-Id nach den Funktionen benennen?

Ich glaube fast, dass das am Ende übersichtlicher ist. Nur bei den Menu-Tiles müssten wir den {{ index }}-Trick verwenden - oder vielleicht {{ menu.title }} nehmen. Nur so eine Idee.

**Comment by lthuong** [comment]
Ich finde es ist auch ein guter Vorschlag. Also bei der Änderung von Main-Menü zu den Menü-Icons glaube ich, dass es gar kein großes Problem ist. Ich push später eine andere Version und dann können wir zusammen schauen, was wir weiter machen sollen

**Comment by sheepyhollow** [comment]
Ich denke, wir schließen das Issue. Well done @lthuong
