### ISSUE TITLE
get rid of lodash

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1466]
Ich habe im skeleton-module diesen Eintrag gefunden:

https://github.com/zentrumnawi/solid-frontend/blob/0b4a1c7d97c6b40c28e2b0fea2c8e36a7b11d869/libs/solid/skeleton/src/lib/solid-skeleton.module.ts#L39

Ich weiß nicht genau, wo `lodash` verwendet wird. So weit ich das sehe, nur hier:

https://github.com/zentrumnawi/solid-frontend/blob/0b4a1c7d97c6b40c28e2b0fea2c8e36a7b11d869/libs/solid/skeleton/src/lib/solid-skeleton.module.ts#L62

Ich weiß nicht, wie relevant das ist, aber mir fällt es immer wieder mal auf - auch bei den dependencies.

**Comment by anhnguyen-98** [comment]
`lodash` wird da verwendet, um die Objekten zu mergen. Das ist ein Dependency von JS Framework, das viele Built-in-Methode für Array, Objekt,... anbietet. Aber wir haben nur da mit der Methode `merge` benutzt. Das steigt die Größe der Bundle-File (siehe da unten bei `vendor.js` mit Size 8.0 MB)
![Screenshot 2022-03-27 at 19 09 45](https://user-images.githubusercontent.com/71195698/160292662-30948530-cb5c-40d1-b0b1-c211f7e5c0cd.png)

ich habe selbe eine Methode geschrieben, die identisch wie `merge` in `lodash` ist. Und der Size der `vendor.js` senkt auf 7.4 MB
![Screenshot 2022-03-27 at 19 07 09](https://user-images.githubusercontent.com/71195698/160292869-a3b5ea8d-7253-4774-ab40-462d9bd1dfad.png)

Also so war das gemeint oder? Dann können wir komplett `lodash` von unserem Code wegnehmen.

**Comment by sheepyhollow** [comment]
Ja, ich denke, das war gemeint! 
Es sind zwar nur 6 kB weniger - aber das macht auch was aus. Wenn Du einen Ersatz hast - super!

**Comment by anhnguyen-98** [comment]
Nöö. 1024 x 0,6 = 614 kB weniger war das. Schon viel.

**Comment by sheepyhollow** [comment]
Um die Uhrzeit kann ich nicht mehr rechnen :wink:
