### ISSUE TITLE
guided-tour Steckbriefkomponente

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#1467]
Beim ersten Öffnen der Steckbriefkomponente soll es eine guided-tour geben. 
Das Design soll wie bei der guide-tour der landing page sein. 
Textvorschläge für die verschiedenen Apps: 

- [x] **Dive:**

Willkommen in den [Titel der Steckbriefkomponente] _(in diesem Fall "Steckbriefe")_! In einer kurzen Tour möchten wir dir die verschiedenen Funktionen dieses Bereichs zeigen.

Hier kannst du zwischen Steckbriefen der selben Gattung wechseln oder den  gerade offenen Steckbrief schließen.  _Links/Rechts-Pfeil + X_

Hier findest du eine Kurzbeschreibung der Pflanze.  _Bereich oberhalb des Bildes_

Hier werden Fotos, Videos oder Audiodateien zu der Pflanze angezeigt. Über die Thumbnails kannst du zwischen diesen wechseln. 

Über diesen Button kannst du die Copyright-Informationen zu den Fotos, Videos oder Audios abrufen. 

Über diesen Button erreichst du weitere Funktionen wie die Deep-Zoom-Funktion von hochauflösenden Bildern, Audiodateien zum Bild oder kurze Fotobeschreibungstexte.     _...-Button_

In diesem Bereich sind wichtige Bestimmungseigenschaften der Pflanze dargestellt. 

Wir wünschen dir viel Spaß beim Erkunden und Bestimmen verschiedener Pflanzen.
 

- [x] **GeoMat:** 

Willkommen in den [Titel der Steckbriefkomponente] _(in diesem Fall "Steckbriefe")_! In einer kurzen Tour möchten wir dir die verschiedenen Funktionen dieses Bereichs zeigen.

Hier kannst du zwischen Steckbriefen der selben Klasse wechseln oder den gerade offenen Steckbrief schließen.  _Links/Rechts-Pfeil + X_

Hier werden hochauflösende Fotos zu dem Mineral angezeigt. Über die Thumbnails kannst du zwischen diesen wechseln. 

Über diesen Button kannst du die Copyright-Informationen der Fotos abrufen. 

Über diesen Button erreichst du weitere Funktionen wie die Deep-Zoom-Funktion von hochauflösenden Bildern, Audiodateien zum Bild oder kurze Fotobeschreibungstexte. _...-Button_

In diesem Bereich sind wichtige Bestimmungseigenschaften des Minerals  übersichtlich dargestellt. 

Wir wünschen dir viel Spaß beim Erkunden und Bestimmen verschiedener Minerale.

- [x] **PLANTY:** 

Willkommen in den [Titel der Steckbriefkomponente] _(in diesem Fall "Steckbriefe")_! In einer kurzen Tour möchten wir dir die verschiedenen Funktionen dieses Bereichs zeigen.

Hier kannst du zwischen Steckbriefen der selben Rebsorte wechseln oder den gerade offenen Steckbrief schließen.  _Links/Rechts-Pfeil + X_ 

Hier werden Fotos, Videos oder Audiodateien zu einer Rebe angezeigt. Über die Thumbnails kannst du zwischen diesen wechseln. 

Über diesen Button kannst du die Copyright-Informationen zu den Fotos, Videos oder Audios abrufen. 

Über diesen Button erreichst du weitere Funktionen wie die Deep-Zoom-Funktion von hochauflösenden Bildern, Audiodateien zum Bild oder kurze Fotobeschreibungstexte. _...-Button_

In diesem Bereich sind die charakteristische Eigenschaften der Rebe  übersichtlich dargestellt. 

Wir wünschen dir viel Spaß beim Erkunden und Bestimmen verschiedener Reben.

- [x] **AIS:** 

Willkommen in den [Titel der Steckbriefkomponente] _(in diesem Fall "Fundstücke")_! In einer kurzen Tour möchten wir dir die verschiedenen Funktionen dieses Bereichs zeigen.

Hier kannst du zwischen Steckbriefen der selben Keramikgattung wechseln oder den gerade offenen Steckbrief schließen.  _Links/Rechts-Pfeil + X_ 

Hier werden Fotos, Videos oder Audiodateien zu einem Fundstück angezeigt. Über die Thumbnails kannst du zwischen diesen wechseln. 

Über diesen Button kannst du die Copyright-Informationen zu den Fotos, Videos oder Audios abrufen. 

Über diesen Button erreichst du weitere Funktionen wie die Deep-Zoom-Funktion von hochauflösenden Bildern oder kurze Fotobeschreibungstexte. _...-Button_

In diesem Bereich sind die charakteristische Eigenschaften des individuellen Fundstücks  übersichtlich dargestellt. 

Wir wünschen dir viel Spaß beim Erkunden verschiedener Fundstücke.

**Comment by sheepyhollow** [comment]
Fertig oder? Dann bitte schließen.
