### ISSUE TITLE
Startseite überarbeiten

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1481]
Die Startseite sollte reduziert werden, so dass die Menü-Kacheln im Vordergrund stehen.

#### Neuigkeiten
Die Messages sollten nicht mehr automatisch angezeigt werden, sie nehmen viel Platz weg.
Lösungen könnten sein
- ein Expansion-Panel sein
- ein Menüeintrag und ein eigener View (oder ein Teil von `Info`)
- ... ?

#### Landing Banner ("Willkommen bei...")
Das Landing Banner nimmt auch Platz weg und ist eigentlich nur beim ersten Öffnen der App wichtig.
Das Banner könnte...
- Teil des News-Expansion-Panels sein
- mit einer anderen UX geschlossen werden (z.B. mit einem extra Button `Ausblenden` und nicht nur einem ❌ )

Da wir die Messages im Local Storage speichern, können wir auch feststellen, wenn es eine neue Message gibt und z.B. ein [Badge](https://material.angular.io/components/badge/overview) anzeigen (entweder auf einem Expansion Panel oder auf der Menü-Kachel) 

#### Menü-Kacheln
- Das Glossar soll eine eigene Menü-Kachel bekommen
- Die Anzahl der Menu-Tiles sollten immer gerade sein.
  - Bei Custom Components (z.B. GeoMat-Kristallsystemen) wird die Anzahl der Kacheln ungerade. Der Ausgleich kann entweder durch Weglassen des Glossars oder durch das Auftrennen von Info- und Datenschutz (nur in den Kacheln!) gemacht werden.

**Comment by kerstinhartmann** [comment]
**Neuigkeiten:** Expansion-Panel fände ich sinnvoll. Unsere Idee mit den Neuigkeiten auf der Startseite war ja, dass sie schnell und einfach erreichbar sein sollen. Das wären sie irgendwo versteckt im Infobereich nicht (zumal sie im Infobereich ja sowieso auch angezeigt werden). Als schmales Expansion-Panel würden sie aber viel weniger Platz einnehmen als zurzeit. 

**Landing Banner:** hier wäre ich eher für die andere UX, die (hoffentlich) dazu führt, dass die Studis das Banner zumindest einmal zu Beginn lesen und dann bewusst schließen. Auch hier, wäre es in einem Neuigkeiten-Panel eher versteckt und gerade für Neulinge auf der Seite nicht direkt sichtbar. Somit wäre auch die "Begrüßung" durch das Banner nicht gegeben.

**Comment by kerstinhartmann** [comment]
Oder wie seht ihr das?

**Comment by sheepyhollow** [comment]
Wollen wir hier mal auch das Planty-Team fragen @kerstinhartmann ?

**Comment by kerstinhartmann** [comment]
Ja, find ich eine gute Idee. Sie sind ja sowieso relativ stark eingebunden - falls wir dann noch mehr Meinungen und Ideen brauchen könnte ich auch das GeoMat-Team noch fragen

**Comment by sheepyhollow** [comment]
Wir müssen auch noch im Kopf behalten, wie das mit der Tour zusammenpasst und ob sich da Probleme ergeben.
@lthuong können wir die Anzeige von `landing-banner` und `news` so steuern, dass sie erst nach Abschluss der Tour "aktiviert" werden (unabhängig von der Implementierung).

**Comment by lthuong** [comment]
Also wie ich es gerade sehe, haben wir das noch nicht. `news` wird direkt und `landing-banner` nur beim Einstellung angezeigt.

Ich schaue es gleich mal nach, ob es möglich ist 👌

**Comment by sheepyhollow** [comment]
Ja, für die News müssten wir noch eine condition in den Container bauen. Ich bin sowieso noch nicht so richtig zufrieden mit dem hardcoded landing banner... Wir hatten mal ein issue, ob wir das landing-banner wie einen "sticky" message type behandeln. Das hätte den Vorteil, dass die Content-manager den Text selbst anpassen können.

Aber wir warten erstmal, was das Planty-Team zur Startseite sagt.

**Comment by sheepyhollow** [comment]
Weiter in #1773
