### ISSUE TITLE
Quiz: separate components for single and multiple choice

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1485]
Derzeit sind single- und multiple-choice  in einer Komponente zusammen enthalten (getrennt mit `*ngSwitchCase`).

Beide Komponenten sollten getrennt sein in 
- `single-choice-question`
- `multiple-choice-question`

**Comment by sheepyhollow** [comment]
Können wir hier auch die `mat-icons` für correct/incorrect einbauen? Das sollte dann bei allen Fragetypen so sein.

Vielleicht ist es aber schwieriger - es wird ja hier einfach im Text angehängt.

Eigentlich wollte ich ja, dass an Stelle des Radio-Buttons oder der Checkbox ein mat-Icon angezeigt wird.
Aber das habe ich nicht geschafft. Es ist bestimmt möglich, das generische Checkbox-Symbol durch ein anderes auszutauschen, aber das wird ziemlich hacky, glaube ich.

**Comment by lthuong** [comment]
Alles klar. Mal sehen ob ich das hinbekomme 🧐
