### ISSUE TITLE
Quiz: question component

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1487]
Die Quizfrage mit ihren (swipeable) MediaObjects wird aktuell in der einzigen `quiz question` Komponente angezeigt.

Dieser Teil bleibt für jeden Fragentyp jedoch gleich und sollte daher getrennt von dem Antwort-Handling existieren.

Muss dazu eine neue Sub-Component "Question" erzeugt werden? Oder kann der Teil in `quiz main` gemacht werden?

**Comment by sheepyhollow** [comment]
Ich vermute, dass es eine eigene Komponente gibt, die in `quiz main` referenziert wird. Das ist aber vielleicht im Frontend-Team zu diskutieren.

**Comment by sheepyhollow** [comment]
Ich vermute, dass dieses Issue der Auslöser für die question-media-component ist. Vielleicht war das ein Missverständnis und nicht gut formuliert, weil das Issue direkt auf die MediaObjects eingeht...

Ich meinte es eigentlich so:
- die question-component bleibt, wie sie ist - inklusive der Images/Medjaobjects
- [Die Single- und Multiple-Choice Teile](https://github.com/zentrumnawi/solid-frontend/blob/dev/libs/solid/quiz/src/lib/components/question/question.component.html#L46-L128) kommen in jeweils eigene Komponenten (genau wie Ranking, und True/False und werden dann je nach Fragetyp eingebunden.

Also ungefähr so (pseudo-code)
```
<question-component>
  Toolbar 
  Frage...
  Media-Objects (Bilder/Audios/Videos)
  <single-choice-question ngIF type = SC>
  <multiple-choice-question ngIF type = MC>
  <range-question ngIF type = RN>
  <truefalse-question ngIF type = TF>
  <ranking-question ngIF type = RG>
  "Lösung anzeigen"-Button
</question-component>
 ```

**Comment by lthuong** [comment]
Oh nein... ich habe die Aufgabe nicht gut verstanden. Nächstes Mal frage ich nach, wenn irgendwas nicht klar ist...

**Comment by sheepyhollow** [comment]
Na, deswegen schaue ich auch ab und zu nach ;-)

**Comment by sheepyhollow** [comment]
Das war schon in der ersten Implementierung von mkay so und ich fand es immer seltsam. Jetzt ergibt der Subtitle gar keinen Sinn mehr, weil die Überschrift (Tag) in der Toolbar ist.

**Comment by lthuong** [comment]
Das möchte ich dir auch am Ende fragen, ob wir den Text ein bisschen deutlicher machen sollen 😅

**Comment by sheepyhollow** [comment]
Yes please!

**Comment by sheepyhollow** [comment]
Vielleicht auch mit einem Icon. Alternativ könnte sie auch in der Card rechts oben stehen, z.B. so:

![image](https://user-images.githubusercontent.com/13869236/176910939-d2b80f4c-af93-4678-ad1a-9bfef82cd558.png)

Aber das wäre komplizierter - lieber einfach in die Toolbar und die andere Idee ein anderes Mal.

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/177103830-ed396cd9-883b-4367-8ce4-824311b5624f.png)

![image](https://user-images.githubusercontent.com/13869236/177103506-e187e103-55e9-4821-ae38-a0aa37949846.png)

Die Progress Bar müsste bei letzten Frage bei 100% sein und dürfte bei der ersten nicht bei 0% sein (ist wohl nur ein Counter + 1 Problem)
