### ISSUE TITLE
Quiz: start/config

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1556]
Die Quiz-Start-Komponente soll zwei Szenarien erfüllen

a) Schnellstart mit (sinnvollen) Defaults
  - count: 10
  - difficulty: alle (keine Einschränkung)
  - tags: alle (keine Einschränkung)

b) Expertenmodus mit Konfiguration der Quizfragen

Beides funktioniert schon korrekt, aber das UI ist noch nicht so ganz perfekt.

**Comment by sheepyhollow** [comment]
Folgende Punkte müssen wir festlegen

- wird die Config immer angezeigt? 
- question count: slider oder numeric input?
- difficulty: silder oder numeric input?
- tags: dropdown oder liste/"wolke"

**Comment by sheepyhollow** [comment]
@kerstinhartmann @lthuong - vielleicht könnt Ihr auch Eure Ideen einbringen.

**Comment by sheepyhollow** [comment]
Meine Ideen dazu:

> wird die Config immer angezeigt?

Ich könnte mir vorstellen, dass es zwei Buttons gibt: 
- `Schnellstart` --> Quizstart mit Defaultwerten
- `Expertenmodus` --> die Card erweitert sich um die Config-Bedienelemente (könnte auch ein [slide-toggle](https://material.angular.io/components/slide-toggle/overview) sein)

Vorteil: Es gibt einen direkten Weg, das Quiz zu starten; die Bedienelemente verwirren nicht
Nachteil: Wer wirklich Details einstellen will, muss einen extra Schritt gehen (wenn es ein Toggle ist, könnten wir das sogar im local storage speichern)


> question count

Ich finde den Slider als UI-Element eigentlich cool, vor allem auf touch devices. Aber die Zahl sollte als Label neben dem Slider (nicht als thumb label) gezeigt werden.


> difficulty

Es ist noch nicht klar, was der difficulty-Wert aussagt - ist das eine `max-difficulty`? Was ist, wenn ich nur Stufe 2 spielen will? Was ist, wenn ich Stufe 2-3 aber nicht 1 spielen will?

**Comment by sheepyhollow** [comment]
Also, da es keine anderen Vorschläge gibt, würde ich bei meinen Vorschlägen bleiben. Ich habe hier Mockups gemacht:

Quiz-Start Standard:
![QuizStartMockup-01](https://user-images.githubusercontent.com/13869236/174667505-02b06ebc-e0c4-4188-a60f-d1d30a1c00f6.png)

Der `Schnellstart`-Button muss nicht über die ganze Breite gehen. Probier mal aus, wie es gut aussieht.

![QuizStartMockup-02](https://user-images.githubusercontent.com/13869236/174667626-1c49f04d-cc32-4bf3-a59d-b4fc7084a7cb.png)

Beim Öffnen des Expertenmodus sind die Standardeinstellungen gesetzt (10 Fragen, alle Difficulties, alle Tags).

Idee: Sobald ich eine Difficulty (oder ein Tag) auswähle, werden _alle anderen_ deselektiert.
Wenn ich weitere Difficulties/Tags aktiviere, _bleiben_ diese aktiviert; so kann ich alle Kombinationen auswählen:

![QuizStartMockup-03](https://user-images.githubusercontent.com/13869236/174667828-b5b53d78-4b67-4fa0-9407-358fd9ce45f2.png)

**Comment by sheepyhollow** [comment]
**Difficulty** kann (laut Backend) maximal 5 Stufen haben. In GeoMat werden nur 3 verwendet, in Dive alle 5.
Die Konfiguration muss sich der Response von `/quizmeta` dynamisch anpassen und die Optionen anzeigen, die im difficulty-Array angegeben sind.

**Comment by sheepyhollow** [comment]
Die Tags müssen keine echten `mat-chips` sein, es können auch toggle-buttons (wie difficulty) sein, aber ich finde sie dann rounded besser, wenn sich das so stylen lässt.

**Comment by sheepyhollow** [comment]
Farben sind mit dem Mockup nicht festgelegt, hier sind noch Freiheiten; ich habe jetzt erstmal `primary` verwendet (und `accent` für den slider).

Was noch nicht geklärt ist:

- Es gibt kein `deselect all` für Tags (für Difficulties lohnt sich das vielleicht nicht bei maximal 5 items)
- soll der Expertenmodus im `localStorage` persistiert werden?

Vielleicht kann @kerstinhartmann nochmal eine Meinung zu den Mockups und den Fragen abgeben.

**Comment by sheepyhollow** [comment]
Ah - subtiler Hinweis in Mockup; darauf bin ich nicht extra eingegangen: Auch `quiz-start` sollte die standard-toolbar mit `backBtn` haben wie alle Komponenten 😉

**Comment by kerstinhartmann** [comment]
Also das Mockup und deine Beschreibung finde ich so schonmal richtig gut. Ich würde noch ein anderes Wort als "Schnellstart" wählen z.B. nur "Start" oder "Jetzt starten" "Quiz starten" "Selbsttest starten" "Los geht's" damit auch (nach weiteren Einstellungen) im Expertenmodus das Quiz über einen sozusagen neutralen Button gestartet werden kann. 

Gerade bei vielen Tags wie wir es z.B. in Planty erwarten fände ich einen `deselect all` sinnvoll. Selbst für GeoMat wäre es wahrscheinlich schon mal praktisch und da haben wir (zumindest noch) ja relativ überschaulich viele Tags.

Farbschema so relativ schlicht in den App-Farben finde ich gut. Ich frag mich nur ob die accent-Farbe für den Slider in allen Apps gut sichtbar ist. Ist das in AIS nicht so ein helles beige z.B.?

**Comment by sheepyhollow** [comment]
Ich habe noch einen lustigen Bug/Edge Case gefunden...

Die difficulty selection funktioniert super und ist auch dynamisch - ich habe in GeoMat jetzt zwei Fragen mit difficulty = 4 und = 5 eingestellt und es gibt 5 Buttons - yey!

Aber, wenn es Fragen mit `difficulty = 5` gibt und _keine_ Fragen mit `difficulty = 4`, werden trotzdem die Buttons mit 1-4 nummeriert (weil [`index + 1`](https://github.com/zentrumnawi/solid-frontend/blob/f85375c4471e407fed2779a90f19aa58437ebf7e/libs/solid/quiz/src/lib/components/start/start.component.html#L68)). Wenn ich dann `4` auswähle, gibt es keine passende Frage.

Vielleicht sollte in den Buttons nicht ein selbst gezählter Wert (`i`) sondern wirklich die echten Werte von difficulties stehen - auch, wenn es dann `1` `2` `3` `5` ist.

**Comment by sheepyhollow** [comment]
Wofür wird eigentlich [maxDifficulty](https://github.com/zentrumnawi/solid-frontend/blob/f85375c4471e407fed2779a90f19aa58437ebf7e/libs/solid/quiz/src/lib/components/start/start.component.ts#L34) gebraucht? Ist das work in progress oder mittlerweile obsolet?

**Comment by sheepyhollow** [comment]
Und: Bei 5 difficulties und iPhone SE Größe gibt es noch ein Problem:
![image](https://user-images.githubusercontent.com/13869236/176545256-f070d7f9-2ef1-4ca1-a67b-2779e08efac6.png) 😅

**Comment by lthuong** [comment]
> Und: Bei 5 difficulties und iPhone SE Größe gibt es noch ein Problem: ![image](https://user-images.githubusercontent.com/13869236/176545256-f070d7f9-2ef1-4ca1-a67b-2779e08efac6.png) 😅

Ich werde später alle Probleme mit den PC-Layout und Mobile-Layout in einem anderen Push lösen. Das habe ich auch schon notiert

**Comment by lthuong** [comment]
> Aber, wenn es Fragen mit `difficulty = 5` gibt und _keine_ Fragen mit `difficulty = 4`, werden trotzdem die Buttons mit 1-4 nummeriert (weil [`index + 1`](https://github.com/zentrumnawi/solid-frontend/blob/f85375c4471e407fed2779a90f19aa58437ebf7e/libs/solid/quiz/src/lib/components/start/start.component.html#L68)). Wenn ich dann `4` auswähle, gibt es keine passende Frage.
> 
> Vielleicht sollte in den Buttons nicht ein selbst gezählter Wert (`i`) sondern wirklich die echten Werte von difficulties stehen - auch, wenn es dann `1` `2` `3` `5` ist.

Ich habe es auch gemerkt. Aber ich weiß nicht ob es einfach so lassen kann, deswegen habe ich ein selbst gezählter Wert (`i`) genutzt. Wenn du schon so gesagt hast, ändere ich es 👌

**Comment by lthuong** [comment]
Bei der `deselect all`-Frage denke ich, dass wir können die Überschrift als einen Button verwenden: Wenn der User drauf klickt, werden alle Tags abgewählt. Ich weiß aber nicht ob es sinnvoll ist. Anschließen werden alle Tags auch abgewählt, wenn der User den Expertenmodus ausschaltet und wieder einschaltet (aber es ist ein bisschen nervig finde ich)

**Comment by sheepyhollow** [comment]
> Meine Meinung nach, brauchen wir den Expertenmodus nicht im `localStorage` abspeichern

Ja, da stimme ich zu. Ich finde es auch eine gute Idee, wenn die letzte Auswahl gespeichert wird. Nur darf diese nicht genommen werden, wenn der Expertenmodus deaktiviert ist 😉 Dann ist Random angesagt.

**Comment by sheepyhollow** [comment]
> Bei der deselect all-Frage denke ich, dass wir können die Überschrift als einen Button verwenden

Verstehe ich - ich weiß aber nicht, ob das transparent ist und ob man das versteht. Aber ich schaue mir das nochmal an, wenn die Buttons fertig sind. Vielleicht gibt es dann noch eine neue Idee - z.B. eine allgemeinen Reset-to-default-Button?

Und was das Abwählen beim Deaktivieren des Expertenmodus angeht - das fände ich auch nervig. Ich fände es gut, wenn der state persistiert wird so lange ich den View nicht verlasse. Aber wenn wir das auch im localStorage speichern, dann ist es ja persistiert.

**Comment by lthuong** [comment]
Wollen wir alle Tags so anzeigen lassen ?

![Screenshot (116)](https://user-images.githubusercontent.com/33594579/176894185-4dcc45b4-358d-4ef5-a9a9-713359182502.png)

**Comment by sheepyhollow** [comment]
Ja, ich finde das ganz gut so! 🙂 

A couple things:
- etwas mehr "Luft" (Padding/Margins) damit es nicht so gedrängt ist
- ja, alphabetisch nach dem 1. Buchstaben sortieren
- lange Tags kürzen? Auf eine feste Zeichenanzahl, z.b 12: `Geologie/Palä...` (oder einfach nicht so lange Tags nutzen)
- die Breite der Tags sollte nicht größer sein als Slider und Difficulty-Buttons

Alternativ könnten wir auch die Überschriften anders platzieren, nämlich so: 

![image](https://user-images.githubusercontent.com/13869236/176909757-1a066acd-04e9-4e18-bc7c-a79db256fd39.png)

Ich glaube, das macht das Management der Buttons viel einfacher.

**Comment by sheepyhollow** [comment]
Und _dann_ könnten wir auch den Reset-Button in die gleiche Zeile am rechten Rand bringen.

![image](https://user-images.githubusercontent.com/13869236/176910360-30ee2a34-a53b-484e-891f-30269584ea4d.png)

(Wir müssten noch ein gutes Icon auswählen)

**Comment by lthuong** [comment]
Sehr gute Idee !

**Comment by sheepyhollow** [comment]
Ah - ich dachte übrigens, dass das mit den Überschriften immer so ist, nicht nur im mobile-view 😅 
Was meinst Du?

**Comment by sheepyhollow** [comment]
Und ich denke, dass auch die Difficulty einen Reset-Button haben sollte. 
`onDeselectAll` müsste dann noch gedoppelt werden.

**Comment by lthuong** [comment]
> Ah - ich dachte übrigens, dass das mit den Überschriften immer so ist, nicht nur im mobile-view 😅 Was meinst Du?

Naja, ich habe es ausprobiert und bin aber nicht sicher welche Version besser ist... Dazu brauche ich eure Meinungen 😄

![Screenshot (121)](https://user-images.githubusercontent.com/33594579/177011425-1519cd1c-39c4-447d-947e-b8a2bbca562c.png)
![Screenshot (122)](https://user-images.githubusercontent.com/33594579/177011428-caf363d6-6bc1-4230-be54-2cf7bb85220c.png)

**Comment by sheepyhollow** [comment]
@kerstinhartmann was meinst Du?

Ich mag die 2. Option - wenn es einen einheitlichen Rand gibt 😉 (Buttons auf der gleichen Linie wie die Überschriften)

**Comment by kerstinhartmann** [comment]
Ich finde auch die 2. Option schicker bzw. vor allem etwas übersichtlicher.
