### ISSUE TITLE
Feedback Form nicht scrollable

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1564]
Auf sehr kleinen Bildschirmen (iPhone SE) sind die Buttons "Abbrechen" und "Absenden" nicht sichtbar.

**Comment by sheepyhollow** [comment]
Noch nicht im normalen Contact-Form, oder? Das wäre dann eigentlich das letzte vor Planty Release.

Und wo wir schon dabei sind: Ich würde noch etwas weniger margin vorschlagen.

(Der Media-Detail-Dialog ist sogar fullscreen bei kleinen Bildschirmen)

**Comment by lthuong** [comment]
Ich habe es vergessen 2 panelClass zu verwenden 😅

Wollen wir den Feedback-Dialog fullscreen (beim Handy-Layout) umstellen ? 

![Screenshot (115)](https://user-images.githubusercontent.com/33594579/174158816-8c44bd9b-43a0-4ec0-910a-208b91c00872.png)

**Comment by sheepyhollow** [comment]
Yes please. Ich glaube, das ist die beste UX!
Und noch zusätzlich einen Close Button ✖️ in die Toolbar (wie bei Media Dialog).

**Comment by sheepyhollow** [comment]
Ja, sehr gut - Fullscreen sieht gut aus!

Ich habe noch das hier gesehen:

![image](https://user-images.githubusercontent.com/13869236/174310165-12bee46a-cedc-477c-b8b3-ca7b05d0becc.png)

Wenn ich SEHR viel schreibe, dann gibt es einen overflow. 
https://github.com/zentrumnawi/solid-frontend/blob/ed88254d8b100a55470ef7be95775049b0e5c0d4/libs/solid/skeleton/src/lib/components/feedback/feedback.component.html#L20

Ich habe es hier mit `maxRows` probiert, aber das hat nicht geholfen.

Siehe auch https://material.angular.io/cdk/text-field/overview

**Comment by sheepyhollow** [comment]
Das ist jetz aber auch kein Drama, wer auf dem Smartphone so viel schreibt ist selbst schuld 😅 
Wenn Du einen schnellen Fix findest, gut, ansonsten können wir das auch nachholen.

Und wie war das mit dem Close-Button? 😉

**Comment by lthuong** [comment]
Ich habe gerade den Button eingefügt. Ich schaue später noch mal nach, was ich mit dem Overflow machen soll 🤔 ich muss nun gleich los

**Comment by lthuong** [comment]
Ich habe gerade nachgeschaut und ich sehe, dass `max-height` dann gesetzt werden muss damit es keinen Overflow gibt

**Comment by sheepyhollow** [comment]
ah, also CSS.

Und der Button geht doch bestimmt noch auf die gleiche Höhe wie die Überschrift, Oder? 😉 😇 😂 

Bzw. umgekehrt - die Höhe des Buttons ist perfekt, aber die Überschrift sollte auch da oben hin.
