### ISSUE TITLE
Openseadragon Update

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1596]
Der Dependabot hat ein automatisches Update von Openseadragon vorgeschlagen (in #1595)

Da das eine zentrale Funktion in den Steckbriefen ist, sollten wir diese erst in einem separaten Branch testen.

- branch anlegen
- openseadragon updaten (mit `yarn upgrade openseadragon @types/openseadragon` - nochmal überprüfen, ob das so stimmt!)
- ausprobieren
- wenn alles funktioniert: Branch mergen 

(Der dependabot-PR sollte sich selbst löschen)

**Comment by lthuong** [comment]
Ich bekomme immer diese Warnmeldung egal vor oder nach dem Update. Sonst hat alles gut geklappt 

![Screenshot (130)](https://user-images.githubusercontent.com/33594579/193336384-31e197df-f324-4330-b0ce-cd636763d944.png)

**Comment by lthuong** [comment]
Das Problem beim Commit wurde durch die Aktualisierung des canvas gelöst
