### ISSUE TITLE
@Select decorator deprecation

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1614]
Mit @ngxs/store^3.7.4 ist der `@Select`-Decorator deprecated (siehe #1613)

Eine [Lösung](https://github.com/ngxs/store/issues/1854#issuecomment-1167955493
) besteht darin, den Decorator zu entfernen und die store-select-Funktion zu ersetzen:

https://www.ngxs.io/concepts/select#store-select-function

Dies muss für alle 24 Code-Stellen gemacht werden.

**Comment by lthuong** [comment]
Nach dem neuesten Update von NGXS (3.7.5) funktioniert das @Select-Decorator wieder:

https://github.com/ngxs/store/blob/master/CHANGELOG.md#375-2022-08-08

Laut diesem Kommentar https://github.com/ngxs/store/issues/1854#issuecomment-1208689828 wird eine bessere Lösung für das `@Select-Decorator deprecated`-Problem bei @ngxs/store^3.8 gegeben. 

Ich glaube, dass wir erstmal darauf warten sollen. Was denkst du ? @sheepyhollow

**Comment by sheepyhollow** [comment]
Ja, wenn das so ist, dann warten wir, wie es damit weitergeht!

Schön, wenn sich Probleme von selbst lösen 😁  Aber ich glaube, diese deprecation war auch... unpopulär.

Dann führe doch mal das Upgrade manuell im angular-update-branch durch (`yarn upgrade ngxs^3.7.5` - _glaube_ ich, nochmal in die yarn Doku schauen) und schau, was passiert.

**Comment by sheepyhollow** [comment]
können wir auch schließen, oder?
