### ISSUE TITLE
Neue App Wabe

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1719]
Wir bekommen eine neue s.o.l.i.d.-App mit dem Namen **WABE**.

Hierzu muss das Frontend-monorepo um eine neue App erweitert werden.

Das letzte Mal wurde das mit AIS in #773 gemacht - vielleicht hilft das als Referenz.
Es gibt einen automatisierten Weg mit der Angular-Cli und eine manuelle Lösung.

**Comment by sheepyhollow** [comment]
Ich würde vorschlagen, das erst nach Abschluss des Angular Updates zu machen.

**Comment by sheepyhollow** [comment]
In Zusammenhang mit dem ng-add Test-Problem - das Anlegen der neuen App sollte _eigentlich_ so funktionieren:

```
$ ng-add wabe
```

Es kann aber sein, dass noch Options angegeben werden müssen (ich bin aber nicht sicher). Einfach in einem neuen Branch ausprobieren. Es sollte dann einen neuen Folder in `/apps` erstellen, sowie die meisten (vielleicht aber nicht alle) Einträge in den zentralen Files (angular.json etc.). 

Danach müsstest Du wahrscheinlich nochmal durchgehen und suchen, wo überall weitere Einträge gemacht werden müssen; Suche nach "geomat" oder "dive" (oder planty oder ais...) sollten alle Files zeigen, in denen Informationen zu den einzelnen Apps stehen.

**Comment by lthuong** [comment]
Haben wir schon einen Endpoint für die neue App ?

**Comment by sheepyhollow** [comment]
Nein, bitte erstmal GeoMat-Staging übernehmen. Das Backend existiert noch gar nicht. Ich glaube, das geht aber relativ schnell, die Profiles sind nicht sehr kompliziert.

Ich schicke Dir noch ein Mockup von den WABE-Leuten für das Theme.

**Comment by sheepyhollow** [comment]
Bitte auch an die .github Actions denken. Am besten sowohl in `build.yml` als auch in `build-backup` hinzufügen.

Ich muss aber noch die Subdomains registrieren lassen, die gibt es auch noch nicht.

**Comment by sheepyhollow** [comment]
Die Subdomain wird um 12:00 heute aktiv.

**Comment by sheepyhollow** [comment]
Wabe läuft ja - dann können wir das Issue schließen.

Gut gemacht!
