### ISSUE TITLE
local build Warnung

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1758]
`Project 'solid-skeleton' contains extension with invalid name`

Das sollten wir noch weg bekommen. Scheint mit `nx` zusammenzuhängen.

**Comment by lthuong** [comment]
Ich glaube, dass das Problem hier ist: https://github.com/zentrumnawi/solid-frontend/blob/09414b1aafcefee79cf82042b40e3b049fc2d79a/angular.json#L874

Wenn ich diese Zeile weglasse, wird die Warning nicht mehr gezeigt. Ich weiß aber noch nicht, wieso wir die Zeile auf diese Stelle brauchen 🤔

**Comment by sheepyhollow** [comment]
Ich auch nicht. Wenn sonst alles funktioniert (schau auch mal Tests und local build an), dann weg damit. Eigentlich werden hier - wenn ich die schematics richtig verstehe - dependencies eingebunden, die für die spezifische Library (hier: solid-skeleton) gelten. 

Ich wüsste nicht, dass wir irgendwo in unseren libs spezifische dependencies haben, deswegen ... 🤷

**Comment by lthuong** [comment]
Ich kann erstmal die Zeile weglassen oder wir können auch wie diesen Kommentar empfiehlt: 

https://github.com/nrwl/nx/issues/11138#issuecomment-1190516733

Die `reader.js` Datei ändern (ich habe ausprobiert, `dependencies` in dem Project-Extensions hinzufügen und es hat gut geklappt, also die App funktioniert). Aber weil die Datei im node_modules befindet, müssen wir noch ein paar Sachen machen, damit die Datei gepusht werden kann.

Was denkst du ?

**Comment by sheepyhollow** [comment]
Zeile weglassen. Ich glaube nicht, dass wir das brauchen.
