### ISSUE TITLE
Guided Tour issues

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1772]
Wir haben zwei Probleme bei der Tour: 
1. die Profile-Tour startet im Moment mit einer fest eingestellten Verzögerung, um das Laden der Profiles zu ermöglichen. Das sollten wir so abfangen, dass die Tour erst startet, wenn alles geladen ist. Evtl. gibt es hier eine Verbindung zu #1558? Dort wird ja der loading/loaded-Status definiert
2. Die Tour ist nicht robust für fehlende `id`s in den Komponenten - z.B. funktioniert der Copyright-Step nicht, wenn kein Bild existiert (dann gibt es den Tag/Container und die `id` wird nicht gefunden).

- [x] Tour erst starten, wenn alle Profiles geladen sind
- [x] Können wir die Tour robuster machen und den Fall, dass eine element-id nicht existiert, abfangen?

**Comment by lthuong** [comment]
Soll die Verzögerung nur beim Start der Tour eliminiert werden ?
