### ISSUE TITLE
Startseite overhaul

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1773]
- [x] Ein Popup/Dialog für das landing banner
- [x] ein [Badge ](https://material.angular.io/components/badge/overview) auf der Info-Tile in der landing-component wenn es eine neue Message gibt

**Comment by sheepyhollow** [comment]
Hinweis zum Badge/new messages: 

Wir können den Local Storage nutzen; hier werden die Messages gespeichert und hier können wir implizit einen Read-Status ableiten (glaube ich).

**Comment by sheepyhollow** [comment]
Ich würde das noch um Folgendes ergänzen, wenn es nicht zu kompliziert ist:
- Wenn der Bildschirm klein ist, erscheint das Popup (je nach `hide_landing_banner` status im local storage)
- Wenn der Bildschirm groß ist (= Desktop-Ansicht) wird das landing banner so angezeigt, wie es im Moment ist (kein Popup)

Breakpoint wie FixedLayout in der skeleton/base-layout component.

**Comment by lthuong** [comment]
Beim dem Popup/Dialog meinst du, dass wir statt der sticky Message, die wir jetzt haben, eine eigene Dialog (wie Report-Message) für das landing banner erstellen ?

**Comment by sheepyhollow** [comment]
Genau! Du kannst hier wahrscheinlich die Infrastruktur aus dem Report-Dialog nutzen oder viel kopieren.

Wenn `hide_landing_banner = false` wird beim Öffnen der Dialog mit dem landing-banner-content angezeigt (noch bevor die Tour beginnt).

Dazu sollte es vielleicht auch einen expliziten "nicht mehr anzeigen"-Button geben.

(ich bin noch nicht zu 100% mit der UX zufrieden, aber das müssen wir auch mit den Usern ausprobieren, glaube ich)

**Comment by lthuong** [comment]
Wir haben jetzt eine eigene Komponente in jeder App für das landing banner content (landing-banner-content.component), was ich redundant finde, weil wir nun eine zentrale Dialog-Komponente für das landing banner erstellen (das führt auch zu einigen Probleme beim Styling,...). Deswegen glaube ich, dass wir alle Info in dem landing-banner-content.component in eine json-Datei speichern und wir können dann diese Info von solid-core-config zugreifen. Wie z.B hier abgebildet:

![Screenshot (153)](https://user-images.githubusercontent.com/33594579/203808976-e0096d4a-e0a7-483c-9b97-a7bc3fff5f47.png)

Was denkst du ? @sheepyhollow

**Comment by sheepyhollow** [comment]
Sehr gute Idee! Mich hat diese Doppelstruktur auch schon gestört. Da der Part so oder so nicht user-editable sein soll (#1767), können wir mit einem json Code einsparen.

Links (md oder html) würden auch funktionieren, oder?

(Ich halte Links nicht für eine schlaue Idee, aber vielleicht wünscht es sich jemand)

**Comment by lthuong** [comment]
Links wären auch sinnvoll, wenn der Content von verschiedenen Bestandteile aufgebaut wird z.B in userem Fall den `i-tag` in dem `p-tag` nutzt 🤔

**Comment by sheepyhollow** [comment]
Ah - wir sollten gar nicht großartig mit `<p>` und `<i>`-Tags arbeiten, sondern direkt ein Markdown-Feld daraus machen. Dann sind wir ja ganz frei.
