### ISSUE TITLE
quiz tag Breite (expert mode)

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1869]
![image](https://user-images.githubusercontent.com/13869236/222861860-a0f53609-e3a9-4518-8de5-62779b977c0b.png)

Die Chips sind zu kurz wenn es nur wenige Tags gibt.

**Comment by sheepyhollow** [comment]
Wir haben an der Stelle schon Änderungen gemacht - aber am Beispiel GeoMat, wo es sehr viele Tags gibt.
Das Problem tritt bei wenigen Tags auf durch eine Kombination aus `space-between` und `width` in [libs\solid\quiz\src\lib\components\start\start.component.scss](https://github.com/zentrumnawi/solid-frontend/blob/bb/quiz-fix/libs/solid/quiz/src/lib/components/start/start.component.scss#L184)

**Comment by lthuong** [comment]
Also wollen wir die Breite des Tages ändern, wenn es wenigen Tags gibt oder ? Ich habe gerade versucht, die Breite des `mat-chip-list` auf 100% gesetzt und es sieht nur ein bisschen besser aus. Was denkst du ? 

![Screenshot (162)](https://user-images.githubusercontent.com/33594579/222977218-81692b5f-2383-406c-8e62-ac0491e1726c.jpg)

**Comment by sheepyhollow** [comment]
Eigentlich müssten wir bei kleinen Bildschirmen dann weniger als 3 Items pro Zeile haben.
Ich erinnere mich aber, dass es schon ein ziemlicher Hustle war, das so zu machen, wie es jetzt ist - und ich erinnere mich nicht mehr, wie wir die Anzahl der Chips pro Zeile dynamisch machen können. War das die [Breite der mat-chips](https://github.com/zentrumnawi/solid-frontend/blob/bb/quiz-fix/libs/solid/quiz/src/lib/components/start/start.component.scss#L198-L208)?

**Comment by lthuong** [comment]
Yup. Das war die [Breite der mat-chips](https://github.com/zentrumnawi/solid-frontend/blob/bb/quiz-fix/libs/solid/quiz/src/lib/components/start/start.component.scss#L198-L208).

Ich glaube, wir können `ngClass` hier benutzen um die Fälle zu unterscheiden. Z.b wenn es weniger als 10 Tags gibts, können wir mal die Breite ein bisschen höher setzen 🤔

**Comment by sheepyhollow** [comment]
Oh, das wäre natürlich prima! Das Konzept kenne ich nicht.

**Comment by sheepyhollow** [comment]
Super gelöst! 🎉
