### ISSUE TITLE
Leere Tag-Anzeige ausblenden

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1871]
Wenn keine Tags da sind, sollte im Kopf der Frage auch "Tag:" nicht angezeigt werden:

![image](https://user-images.githubusercontent.com/13869236/222863762-36d1ca3e-1981-4cc2-9f37-74cf9ac58643.png)

Zu lösen in [libs\solid\quiz\src\lib\components\question\question.component.html](https://github.com/zentrumnawi/solid-frontend/blob/bb/quiz-fix/libs/solid/quiz/src/lib/components/question/question.component.html#L17)

**Comment by sheepyhollow** [comment]
Das <span>-Element mit einem `*ngIF="question.tags.length !== 0"` funktioniert - führt aber zu einem Umbruch.

**Comment by sheepyhollow** [comment]
Warum überhaupt ein `span`?

**Comment by lthuong** [comment]
Es könnte sein, dass ich den vorherigen Code benutzt habe. Ich weiß auch nicht wieso `span` da verwendet wird
