### ISSUE TITLE
Slideshow default icon size

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1873]
Wenn bei einer Slideshow kein "title image" gesetzt ist, dann wird das App-Icon verwendet.
Im Fall von Planty gibt es hier ein Größenproblem:

![image](https://user-images.githubusercontent.com/13869236/223099248-7742f7d4-d8b3-444d-a00e-11f9b324e76e.png)

**Comment by lthuong** [comment]
Das Problem tritt auf, weil das `icon.svg` von Planty so gesetzt ist:

![Screenshot (173)](https://user-images.githubusercontent.com/33594579/227270313-0ac0bdaa-f4af-4a36-bbf8-c97bf71e23c8.png)

Wir können eigentlich diese Werte ändern damit es kleiner ist (Z.b hier 100x100px)
![Screenshot (174)](https://user-images.githubusercontent.com/33594579/227270672-eb0e2c9e-58af-4fb5-9837-eb3c1804308e.png)

**Comment by lthuong** [comment]
Yup, ich habe das Problem in dem neuen Branch auch so gelöst
