### ISSUE TITLE
PLANTY-Frontend: Kacheln Startseite

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/solid-frontend#1896]
Die neue Lösung mit der responsiven Verteilung gefällt uns schon gut, aber ein Vorschlag wäre, diese immer symmetrisch zu verteilen. Aktuell ist es so, dass es auch mal sein kann, dass in der oberen Ebene vier Kacheln anzeigt werden und unten zwei. Anbei ein Mock-Up für Tablet und Desktop. @sheepyhollow 

![Startseite Desktop 1500x980_Mockup1](https://github.com/zentrumnawi/solid-frontend/assets/132896759/d63de5c7-d017-4447-8cde-7f12947975e8)

![Startseite iPad Pro H 810x1080_Mockup1](https://github.com/zentrumnawi/solid-frontend/assets/132896759/373d36c8-dfe9-4edc-b6f9-e63aac41f1e5)

**Comment by sheepyhollow** [comment]
...und wenn es mal nicht aufgeht? 😉 

Da muss @lthuong mal überlegen, wie das möglich wäre. Klingt nach Mathe, da bin ich raus...
