### ISSUE TITLE
PLANTY-Frontend: Verschieden farbige „Balken“ im Steckbrief

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/solid-frontend#1897]
Wir haben das aktuelle Design der Ebenen im Steckbrief intern einmal ein paar Personen gezeigt und die Rückmeldung war, dass die unterschiedlich farbigen Streifen das ganze irgendwie unruhig machen und vom Inhalt ablenken. Anbei ein Vorschlag als Mock-Up ohne Streifen in der dritten Ebene und mit leichter Farbabstufung in den Überschriften. @sheepyhollow 

![neueFormatierung_PLANTYSteckbrief](https://github.com/zentrumnawi/solid-frontend/assets/132896759/3233fe07-14eb-464c-84e3-9112fc83db30)

**Comment by sheepyhollow** [comment]
@lthuong - das müsste doch mit unserem theme und mat-palette möglich sein, doer?
Dann wäre es für alle Apps ein hellerer Ton von der primary color sein, klingt doch gut.

**Comment by ypeters** [comment]
Viktoria sagte mir gerade, es ist die gleiche Primärfarbe aber mit einem Transparenzwert von ca. 35 % (falls das euch hilft ;))

**Comment by sheepyhollow** [comment]
Nur bedingt - wir arbeiten mit einer vorgegebenen Palette (je App), die wir selbst definieren können. Das sind aber echte Töne und wir arbeiten hier nicht mit Transparenzen. In der Palette sind auch hellere Schattierungen enthalten, die mehr oder weniger automatisch generiert werden - hier kann man damit rumspielen: http://mcg.mbitson.com

Oben die PLANTY-Farbe eingeben und dann gucken, welche "Zahl" passt - 500 entspricht dann der Originalfarbe.

**Comment by ypeters** [comment]
Direkt geschaut - es wäre dann die 100 (#e4eaba) :)
