### ISSUE TITLE
PLANTY-Frontend: Formatierungsvorschläge für die Baumstruktur

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/solid-frontend#1900]
Da die Baumstruktur mit den neuen Pflanzen wächst, hatten wir in unserem damaligen Briefing schon mal einen Formatvorschlag gemacht, den wir gerne diskutieren würden. 😊

@sheepyhollow 

![PLANTY2Learn_Baumstruktur_2_Formatierungsvorschlag](https://github.com/zentrumnawi/solid-frontend/assets/132896759/178bdc55-a183-4810-bf66-30f7e33ec513)

**Comment by sheepyhollow** [comment]
@lthuong - hier könntest Du Ideen einbringen.

Vielleicht sollten wir die Einrückung links generell verringern?

**Comment by sheepyhollow** [comment]
@ypeters - lange Namen könnt Ihr auch einfach mal ausprobieren 😉

**Comment by ypeters** [comment]
Haha ja der Hinweis zum langen Namen ist noch ein Relikt aus dem ersten Briefing. 

Das haben wir schon mal getestet. Ich hab aber eben im Staging auch mal bei einer der Reben, die im Tree unter Test eingeordnet sind, den Namen geändert. Da könnt ihr es dann sehen, wenn ihr den Einzug verändert. :)

**Comment by sheepyhollow** [comment]
Das ist okay so, oder? Es bricht halt um. Bei zwei Zeilen sieht es sogar noch nicht mal ganz furchtbar aus.

**Comment by ypeters** [comment]
Ja das ist auf jeden Fall ok! :)
