### ISSUE TITLE
PLANTY-Frontend: Feld "Familie" fehlt

### ISSUE THREAD

**Issue by vvvika** [zentrumnawi/solid-frontend#1950]
Aktuell fehlt das Feld "Familie - botanischer Name" unter der Kategorie "Taxonomie und Lebensweise" im Frontend bei den Gehölzen. Im Steckbrief (im Backend) ist dieser vorhanden.
🍃

![Steckbrief_Gehoelze](https://github.com/zentrumnawi/solid-frontend/assets/95678980/4b5a0b5a-f64a-4852-8705-bbbcbecedd2a)

**Comment by sheepyhollow** [comment]
Hm... ich glaube wir haben hier noch ein Problem mit unserem Enum/Ref-Workaround...

Im  [profile definition service](https://github.com/zentrumnawi/solid-frontend/blob/dev/libs/solid/profile/src/lib/services/profile-definition.service.ts#L128) nutzen wir die Enum-Property `oneOf[0]`, um die Referenzen zu finden.

Family und zB. "in Deutschland heimisch" (`de_domestic`) haben aber eine `allOf`-Property:

![image](https://github.com/zentrumnawi/solid-frontend/assets/13869236/83544210-c7c5-4e92-8828-d7eabe79aae7)

**Comment by sheepyhollow** [comment]
Wir können den Workaround erweitern durch
```
if (schema.oneOf || schema.allOf) (schema.type as ParameterType) = 'string'; // workaround for enums
```

It ain't pretty, aber dann tauchen die fehlenden Eigenschaften auf.

**Comment by sheepyhollow** [comment]
Die Enums müssen wir das dann (ggf. in Zusammenarbeit mit dem Backend) sauber lösen.
