### ISSUE TITLE
Melde-Button - Design-Vorschlag

### ISSUE THREAD

**Issue by vvvika** [zentrumnawi/solid-frontend#2002]
Ich bin mir nicht mehr sicher, ob mein Entwurf für den Lautsprecher-Button + Icon für die News-Anzahl nicht passend war oder einfach untergegangen ist. Daher würde ich die Dateien hier hoch laden, und die Admins können das Thema schließen, falls nicht mehr aktuell.

![MockUp Infos 2](https://github.com/zentrumnawi/solid-frontend/assets/95678980/b00dbcd2-5b21-4ba7-90a3-92c9f5197c26)

Falls ihr die offene Datei (siehe auch Mail an Bertram vom 11.01.23) benötigt, sagt mir hier Bescheid :)

**Comment by sheepyhollow** [comment]
Ich glaube, das ist für Planty umgesetzt.
