### ISSUE TITLE
Styling allgemein

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#21]
Hier können allgemeine Styling ToDos hinzugefügt hat.
- [ ] Theming - definieren (Primary und Accent Color ändern)
- [ ] Toolbar der Steckbrief-Detailansicht anders färben.
- [ ] Formatierung der Steckbriefe (Überschriften fett, etwas mehr Padding links)
- [ ] Überlauf im Quiz
- [ ] Landingpage: Icons & Schrift größer (relativ zur Card) mehr Abstand Icon <-> Schrift

**Comment by sheepyhollow** [comment]
Ich blockiere mal, bei einigen Dingen ist es besser, zu warten, bis die Features fertig sind. Aber wir werden gegen Ende nochmal einen Design-Review machen.
