### ISSUE TITLE
Slideshow (Bestimmungshelfer)

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#231]
Der Bestimmungshelfer sollte nicht hart als HTML codiert sein, sondern aus der DB kommen.
Hierfür müssen im Backend die entsprechenden Strukturen geschaffen werden.

**Comment by sheepyhollow** [comment]
@mkay-sh entwirft hierfür ein passendes Objekt.

**Comment by mkay-sh** [comment]
Vorschlag:
```typescript
interface Slideshow {
  title: string; // Title for the menu entry
  pages: SlideshowPage[];
}

interface SlideshowPage {
  title: string; // Page title
  text: string; // Markdown content
  position: int; // Position in the slideshow
}
```

Da in dem Content ja auch Bilder sein können, müssten die irgendwie aus dem CDN kommen. Ich weiß da nicht genau wie das funktioniert, ob die in die DB kommen oder so.

**Comment by sheepyhollow** [comment]
Ist es sinnvoll, den `helper` jetzt schon umzubauen und den Content (wie beschrieben) in ein JSON-File zu schreiben? Das würde den Stand im Vergleich zum gardcoded HTML evtl. schon vereinfachen.
Der aktuelle Inhalt wird in den kommenden Tagen nochmal massiv überarbeitet.

**Comment by mkay-sh** [comment]
Ich würde sagen nein, da der ja später in die DB soll.

**Comment by sheepyhollow** [comment]
Zu den Bildern: CDN ist schlau, aber einfach in die DB laden geht nicht, da die Bilder nicht vom gallery-endpoint mitgenommen werden sollen. 
Frage an @chgad, wie wir das lösen. Vllt. schreiben wir das vorübergehend in die Assets.

**Comment by mkay-sh** [comment]
Würde ich an dieser Stelle so vorschlagen.

**Comment by sheepyhollow** [comment]
und Bilder in die Assets und direkt verlinken?

**Comment by mkay-sh** [comment]
Wenn da weitere Bilder hinzukommen, pack die erstmal in `/assets/determination/….` Und nutze nen absoluten Pfad im HTML im gleichen Format.

**Comment by chgad** [comment]
[Why?](https://github.com/GeoMatDigital/web-geomat/issues/231#issuecomment-532258594)
Warum ist CDN nicht möglich? Oder schwer? Ein upload ins CDN ist EINE Zeile... literally.

**Comment by sheepyhollow** [comment]
> Warum ist CDN nicht möglich? Oder schwer? Ein upload ins CDN ist EINE Zeile... literally.

gemeint war nur, dass sie im Gallery-Endpoint ausgegeben werden, wenn wir sie einfach in der DB hochladen wie Mineralbilder. Wobei ich mir mit Online-status und `sort_list` gar nicht sicher bin...

**Comment by sheepyhollow** [comment]
Ich denke, wir können das hier schließen, sobald die Anzeige der Bilder erledigt ist. Für die bestehende GeoMat-Production ändern wir das nicht und sehen das für das neue DivE-Backend vor.

**Comment by mkay-sh** [comment]
@sheepyhollow @LarsWars Ich habe eine initiale Version der Slideshows gebaut. Viel war an der Stelle auch nicht zu ändern. Die Bilder hab ich erstmal noch rausgelassen, da wir uns doch drauf geeinigt hatten auch in der Slideshow die PhotographModels zu verwenden. Wenn ihr es auch schon vorher mit dem anderen Model braucht sagt einfach Bescheid.

**Comment by sheepyhollow** [comment]
Eigentlich haben wir nun alles, was wir brauchen.
