### ISSUE TITLE
Kristallsysteme Seitenverhältnis

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#236]
Bei der isometrischen/orthographischen Ansicht (`camera = isocam`) wird das Modell beim Ändern der Fenstergröße verzerrt.
Bei der perspektivischen Ansicht (`camera = perspectivecam`) bleibt das Verhältnis korrekt.

**Comment by sheepyhollow** [comment]
Nach den letzten Überarbeitungen ist der viewport sehr klein geworden.
Ist das hier absichtlich rausgeflogen?
https://github.com/GeoMatDigital/web-geomat/blob/df32a1c033fa13c2f8f36cc1de500faefcc4e337/src/app/modules/crystalsystem/components/crystalsystemdetail/crystalsystemdetail.component.scss#L3

**Comment by mkay-sh** [comment]
Jo stimmt. Nicht ganz absichtlich, aber war auch nicht mehr richtig so. Ist korrigiert und live.
