### ISSUE TITLE
Trivialname anzeigen

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#246]
Im Steckbrief `trivial_name` aus der db anzeigen, sofern vorhanden.
Anzeigen unter Mineralname, vor chem. Formel

**Comment by sheepyhollow** [comment]
vgl. https://github.com/GeoMatDigital/web-geomat/issues/2#issuecomment-457933796

**Comment by mkay-sh** [comment]
Ich hatte das so verstanden, dass der Trivialname nur angezeigt werden soll wenn er sich unterscheidet. Bsp: https://geomat.netlify.com/profile/115

**Comment by sheepyhollow** [comment]
zur Dokumentation: `trivial_name` sollte eigentlich gar keine Namen enthalten, die identisch zu `variety` oder `minerals` sind. Das ist effektiv eine Art DB-Artefakt, Klärung steht aus.

**Comment by mkay-sh** [comment]
Ist das ganze inzwischen geklärt?

**Comment by sheepyhollow** [comment]
Nein, wartet noch aufs Backend.

**Comment by sheepyhollow** [comment]
Im Backend ist nun "alles richtig": Jedes Mineral hat einen `mineralname` und hat nur `variety` und `trivialname`, wenn es dieser Eintrag sinnvoll ist.

**Comment by mkay-sh** [comment]
Mit der Abstraktion des `ProfileModels` wären solche Anpassungen nicht mehr so einfach. Die Datenlage dafür müsste also eindeutig sein.
