### ISSUE TITLE
Update Notification

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#343]
Da wir den ServiceWorker benutzen ist eine neue Version nicht direkt beim ersten Laden da sondern wird Lazy im Hintergrund geladen. Wir sollten eine Benachrichtigung anzeigen, damit der User Bescheid weiß. Und das Update im Zweifelsfall manuell machen kann.

**Comment by mkay-sh** [comment]
https://angular.io/guide/service-worker-communications

**Comment by sheepyhollow** [comment]
Thinking of it... ich bin mit den Notifications  bzw. dem Changelog (#228 ) auf dem Homescreen noch nicht so richtig glücklich, das ist mir zu aufdringlich. Und den Zugriff auf die Funktionen finde ich wichtiger für die Nutzer. Da könnte ein Snackbar mit "neuer Version" und Verweis auf den Changelog auch den Dienst tun.

**Comment by mkay-sh** [comment]
Alternative wäre nur den neusten Eintrag im Changelog anzuzeigen und den Rest erst wenn man in expandiert. Oder halt ne komplett eigene Changelog Seite im Infobereich.

**Comment by mkay-sh** [comment]
Im Moment wird wenn ein Update zur Verfügung steht einfach ein Dialog geöffnet. Den Content davon kann man gerne anpassen. Aktueller Content:
```html
<h1 mat-dialog-title>Update</h1>
<div mat-dialog-content>
  Es steht eine neue Version der App zur Verfügung.
</div>
```

**Comment by sheepyhollow** [comment]
Da ja ein Button `Update` im Dialog auftaucht, ist alles selbsterklärend und der Text passt so.
