### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#361]
Wie kriegen wir die 35 MP unserer Bilder userfreundlich genutzt?

**Comment by sheepyhollow** [comment]
https://openseadragon.github.io/

**Comment by sheepyhollow** [comment]
Openseadragon kann im Frontend verwendet werden und basiert auf .dzi-Files (DeepZoomImage)
Mit Backend im nächsten Meeting zu klären: 
- File-Struktur im CDN - wie?
- DZI-Format extern erzeugen oder im Backend bei Upload?
- Machen wir das für alle Bilder oder nur für den GeoMat-Bestand? 
  - bzw. Wie zoomt man ansonsten die Pflanzen?
- wie wird ein (ggf. vorhandenes) DZI-Bild im Endpoint ausgeliefert?

**Comment by mkay-sh** [comment]
Alles ist möglich, nichts muss. Allerdings muss das Backend erst die Vorraussetzungen (Auslieferung von dzi files) erfüllen.

**Comment by sheepyhollow** [comment]
Ich denke, das können wir schließen. Confirm?
