### ISSUE TITLE
Vereinigung Steckbrief/Galerie

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#393]
* Gallerieansicht entfernen
* Bildbeschreibung unter das Bild (Ausklappbar)
* Mehrere Bilder im Steckbrief ermöglichen
[Steckbriefe  GeoMat.pdf](https://github.com/GeoMatDigital/web-geomat/files/4097301/Steckbriefe.GeoMat.pdf)
* Zoom in einem eigenen Overlay
<img width="1112" alt="Steckbriefe  GeoMat" src="https://user-images.githubusercontent.com/24921097/72895264-3aea4900-3d1d-11ea-99e4-6e75050260a6.png">
* Steckbrief Startseite
  Baumansicht und Thumbnailansicht (evtl. auch alle Bilder zu einem Steckbrief)
  Thumbnail sortiert nach der Baumreihenfolge und mit Toggle alphabetisch.

**Comment by mkay-sh** [comment]
Die Vereinigung ist grundsätzlich implemtiert. Die Beschreibung fehlt noch, das ergibt aber auch erst sinn wenn Backendseitig die Vereinigung durchgeführt ist.

**Comment by sheepyhollow** [comment]
In einem PR testen nützt vermutlich nichts, weil die Daten (z.B. mehrere Bilder je Mineral) noch nicht geliefert werden, richtig?

**Comment by mkay-sh** [comment]
So ist es. Bisher haben wir immer nur ein Bild. Ist im Preview ja auch schon sichtbar.

**Comment by mkay-sh** [comment]
Feedback Kerstin:
- [ ] Suche in Baum/Grid ermöglichen
- [ ] alleinstehende Kacheln nicht zentrieren
- [ ] selected im Grid markieren

**Comment by mkay-sh** [comment]
Ich verschiebe `Detailansicht mit Zoom, Audio, Beschreibungstext in einem Overlay; keine zusätzliche Toolbar` in #361 #462

**Comment by sheepyhollow** [comment]
Status prüfen bzw. obige Punkte anpassen oder in einzelne Issues aufbrechen.
