### ISSUE TITLE
Quiz-Feedback

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#418]
Die Anzeige mit richtigen/falschen Antworten ist noch nicht perfekt.
Im Sinn von #289 müssten wir noch klarer machen, welche Antworten abgegeben und welche richtig sind. Genauere Beschreibung der Anforderung folgt.

**Comment by mkay-sh** [comment]
Gibt es da inzwischen News? @sheepyhollow

**Comment by sheepyhollow** [comment]
Zunächst sind nur MC-Fragen betroffen. Wir müssen zwei Dinge visualisiert bekommen:

1. Status der Antwort (richtig / falsch - aktuell durch Farbe und Symbol)
2. Welche Antwort wurde gewählt (aktuell durch Anzeige des Feedbacks)

Beispiel hier:
![image](https://user-images.githubusercontent.com/13869236/77190684-fccd9380-6ad9-11ea-9676-8d57c15675b9.png)

Man sieht, was richtig und was falsch war, aber es ist nicht symbolisiert, was ursprünglich ausgewählt wurde. Hierfür müssten wir noch eine passende Visualisierung finden.

Vorschlag:
- ausgewählte Antworten werden nach der Auswertung **fett** angezeigt
- Feedback wird bei ausgewählten Antworten und immer _kursiv_ angezeigt.
- nicht-ausgewählte Antworten bleiben grau (Schrift)

**Comment by sheepyhollow** [comment]
Das Padding zwischen Feedback und Antwort sollte geringer sein bzw. das zur nächsten Antwort größer, so dass eindeutig sichtbar ist, was zusammengehört.

**Comment by sheepyhollow** [comment]
Cool wäre ja, wenn man die nicht-ausgewählten Checkboxen noch anders stylen könnte, aber da geht nicht viel, oder? Z.B. Outlines. Bestenfalls hellgrün, wenn das individuell ohne Verrenkungen möglich ist.

**Comment by sheepyhollow** [comment]
Kerstin hat noch vorgeschlagen, die gesamte Zeile (samt Feedback) bei den ausgewählten Antworten mit in einem hellen Rot/Grünton zu hinterlegen (vgl. Ionic App). Wenn das einfacher ist als die Checkboxen zu färben, dann würden wir das gut finden.

**Comment by mkay-sh** [comment]
@sheepyhollow bist du hiermit inzwischen eigentlich zufrieden? Dann müsste nur noch einmal diese richtig/falsch Debugzeile entfernt werden.

**Comment by sheepyhollow** [comment]
ups... ja 😇

**Comment by sheepyhollow** [comment]
erledigt mit #745
