### ISSUE TITLE
Image Detail Overlay im Steckbrief

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#462]
Audio, Beschreibungstext in einem Overlay; keine zusätzliche Toolbar
Vorraussetzungen im Backend
- [ ] Anpassung SteckbriefModel/PhotographModel

**Comment by sheepyhollow** [comment]
Frage an @chgad @suehtomit ob die Voraussetzungen im Backend mittlerweile existieren.

**Comment by chgad** [comment]
Die da wären?

**Comment by sheepyhollow** [comment]
Ich hatte gehofft, dass ihr das wisst... :wink: Aber ich denke, es ging darum, dass der `photograph` endpoint die o.g. Informationen mitliefert - und das ist ja der Fall.

**Comment by sheepyhollow** [comment]
Klären, wie die UX für das vergrößerte Bild aussehen muss
