### ISSUE TITLE
[DIVE] Grundapp

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#485]
Dive Grundapp aufsetzen und den Prozess dokumentieren bzw. ein CLI Schematic erstellen.
Zu dokumentieren:
- [x] App generieren 
- [x] PWA
- [ ] SW-Config
- [x] Sentry
- [ ] stylePreprocessorOptions
- [ ] Routing Config
- [ ] App Component
- [ ] App Config
- [ ] Development proxy
- [ ] Webmanifest anpassen
- [ ] Component prefix
- [ ] main.ts

**Comment by sheepyhollow** [comment]
Wie sieht es denn hiermit aus - das ist ja auch Voraussetzung für alle weiteren Derivate, oder?
Dann das dürfte das ein entscheidendes Issue sein.

**Comment by sheepyhollow** [comment]
Wenn ich es richtig sehe, sollte auch die DIVE-Zuordnung weg und es sollte ein SOLID-Issue sein.
