### ISSUE TITLE
[DIVE] Icons

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#486]
Anpassen der Icons für Dive für die App #485 
SVG-Icons (apps/dive/src/assets/svg)
- [x] feedback.svg
- [x] quiz.svg
- [ ] profile.svg
- [x] search.svg
- [ ] privacy.svg
- [x] icon.svg

Steckbrief (apps/dive/src/assets/profile)
- [ ] no_image.svg
- [ ] no_thumbnail.svg

App Icon
- [x] apps/dive/src/assets/icons
- [ ] apps/dive/src/favicon.ico

**Comment by sheepyhollow** [comment]
Fixed in #845
