### ISSUE TITLE
Dynamische Profile

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#501]
Die Steckbriefanzeige sollte dynamisch aus der Swagger Definition generiert werden.
Es fehlt noch die korrekte Anzeige von:
- [x] Markdown
- [x] Boolschen Feldern -> Werden zu String Feldern umgewandelt und die Texte kommen aus dem Backend
- [ ] Listen
- [x] Titel/Trivialname irgenwie #551
- [x] Farbe

**Comment by sheepyhollow** [comment]
Müssen die o.g. Anforderungen aktualisiert werden?

**Comment by sheepyhollow** [comment]
Hier müsste auch @chgad was zum Status sagen können, ob/wie das in Swagger angegeben werden kann.

**Comment by sheepyhollow** [comment]
Wir brauchen zusätzlich noch einen Feldtyp für `Farbe`

**Comment by sheepyhollow** [comment]
I think we can start implementing this.

* the custom field type for markdown fields will be `mdstring`
* the custom field type for color fields will be `colstring`

The aforementioned custom field type for lists ("Listen") will not be implemented until needed.

**Comment by sheepyhollow** [comment]
But we should not merge it unless tested - i.e. unless the backend does supply entries with the new fields.

**Comment by sheepyhollow** [comment]
Allgemeine Beschreibung für Custom Fields: 
Im `profile-definition-service` 
https://github.com/zentrumnawi/solid-frontend/blob/702006536383b8192f57fb2396555af7ea015877/libs/solid/profile/src/lib/services/profile-definition.service.ts#L95
werden die von Swagger übermittelten Datentypen erkannt und verarbeitet. Hier können neue custom types hinzugefügt werden. 

Neue custom types müssen auch im `profile-definition-model` und in der `detail.component.ts` angelegt werden und können dann in `detail.component.html` verwendet werden.

**Comment by sheepyhollow** [comment]
In PR #1000 (🎉 !) wird die Basisfunktionalität eines Farbfeldes bereitgestellt. Wie das weitergeht, wird in #1008 verhandelt. Damit können wir dieses Issue erstmal schließen.
