### ISSUE TITLE
[DIVE][GeoMat] Privacy Component

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#510]
In `apps/dive/src/app/privacy` gibt es eine leere Datenschutzkomponente. Diese muss analog zu GeoMat entsprechend passend gefüllt werden.

**Comment by mkay-sh** [comment]
Außerdem könnten wir uns noch die Frage stellen, ob die Datenschutzkomponente von jedem der SOLID benutzen möchte selbst geschrieben werden soll oder ob es doch eine allgemeingültige Variante gäbe. Dann könnten wir sie in Solid auslagern.

**Comment by LarsWars** [comment]
spezifische Datenschutzkomponente ist geschrieben, die allgemeine folgt. Mit Platzhaltern statt Kontaktdaten
Wie umgehen mit Tools wie Sentry

**Comment by sheepyhollow** [comment]
Sentry müsste sich mit einem Standard-Text erledigen lassen @LarsWars

**Comment by sheepyhollow** [comment]
bzw. ist das ja schon geklärt 🙈 

Ich würde die Datenschutzkomponente App-spezifisch lassen, aber mit einem (unserem) default Text befüllen. Ist das möglich @mkay?

**Comment by sheepyhollow** [comment]
Nochmal überarbeiten

**Comment by sheepyhollow** [comment]
Müsste jetzt alles passen.
