### ISSUE TITLE
Quiz QuestionTypes

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#533]
Das Backend unterstützt noch die Question Typen `DragNDrop`, `Hotspot` und `Ranking`. Das Frontend hat noch keine Anzeige dafür.

**Comment by sheepyhollow** [comment]
Ich schließe dieses Issue - für Ranking gibt es ein Neues #744 und die anderen kommen, wenn sie kommen.
Wahrscheinlich werden wir yes/no noch vor Hotspot und drag/drop umsetzen.
