### ISSUE TITLE
diverse Anmerkungen

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#550]
- [x] Glossary Icon fehlt in dive
- [x] Kacheln im ProfileGrid bei wenigen Kachen sollten nicht die komplette Höhe des Bildschirms einnehmen.
- [x] Alle ExpansionPanels im Steckbrief beim öffnen oder wechseln schließen
- [x] Glossary Links nur 0.5em Abstand zum Text
- [x] Landing Page hat leeren Content der zu einer Scrollbar führt.
- [x] Glossar sollte alphabetisch sortiert sein.

**Comment by sheepyhollow** [comment]
Da auch in GeoMat kein spezifisches `Glossary Icon` existiert, würde ich vorschlagen, das gleiche zu nutzen. Ich denke, wir müssen die Icon-Strategie ohnehin mal überdenken - wird sich jeder zukünftige Kunde die Mühe machen oder brauchen wir ein Default-Icon-Set?

**Comment by LarsWars** [comment]
Jeder sollte seine eigenen Icons machen. Vielleicht brauchen wir eine "Icon-Guideline", damit es nicht zu hässlich wird, wenn andere etwas bauen.

**Comment by mkay-sh** [comment]
@LarsWars die Kleinigkeiten sind soweit umgesetzt. Die Icon Strategie sehe ich eher als eigenen Issue.

**Comment by mkay-sh** [comment]
Daher schließe ich den Issue jetzt,.
