### ISSUE TITLE
[DIVE][GeoMat] InfoPageContentComponent

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#595]
In apps/dive/src/app/info-page-content gibt es eine Komponente für den Inhalt der Info Seite. Diese muss noch gefüllt werden.

**Comment by LarsWars** [comment]
html content eingefügt; Logos fehlen noch

**Comment by mkay-sh** [comment]
Dann ist der Issue ja noch nicht fertig;) Nächstes Mal gerne per PR, dann kommen wir uns nicht in die Quere und ich hab die bessere Übersicht. Mit #IssueId in der Commit Message kannst du auf Issues verweisen, dann sieht man super wodrauf sich der Commit bezieht.

**Comment by sheepyhollow** [comment]
Ich kümmere mich drum

**Comment by sheepyhollow** [comment]
Fixed in #845
