### ISSUE TITLE
Neue Icons

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#6]
Anstelle generischer Icon-Pakete sollen die selbst entwickelten Geo-Mat-Icons verwendet werden.

**Comment by mkay-sh** [comment]
Markus hat die Icons so angepasst, dass es keine Strokes mehr gibt und wird eine Webfont daraus generieren. Anschließend kann ich die Icons mithilfe der `MatIconRegistry` für die Material Components registrieren und anschließend überall verwenden.

**Comment by mkay-sh** [comment]
Es ist leider nicht möglich sowohl die MaterialIcons als auch unsere eigenen einzubinden. Daher bräuchten wir auch alle Icons aus der MaterialFont in unserer eigenen wenn wir diese ebenfalls benutzen wollen, oder doch alle Icons seperat als SVG einbinden....

**Comment by sheepyhollow** [comment]
Mit dem erweiterten Funktionsumfang werden wir noch weitere Icons benötigen, außerdem brauchen wir auch eine Umsetzung der Material Icons (oder eigene) für die Basisfunktionen.

Hauptmenü (Hamburger)
Feedback (Kontakt)
Pfeil rechts
Pfeil links
Pfeil oben
Pfeil unten
Kreuz / X ("Schließen)

Kristallsysteme:

- [ ] Achsen/Koordinatensystem ein-/ausblenden
- [ ] Punkte ein-/ausblenden
- [ ] Flächen ein-/ausblenden
- [ ] Millersche Indizes {101} ein-/ausblenden
- [ ] Kamera wechseln

Galerie/Bildansicht:

- [ ] Zoom plus
- [ ] Zoom minus
- [ ] Audio (z.B. Kopfhörer)
- [ ] Audio start
- [ ] Audio stop
- [ ] Audio pause
- [ ] Text anzeigen
- [ ] Skala ein-/ausblenden
- [ ] Grafik-Overlay (z.B. Ebenen)

Quiz:

- [ ] Checkbox checked
- [ ] Checkbox unchecked

**Comment by mkay-sh** [comment]
Da ich vorschlage den ServiceWorker zu verwenden könenn wir auch ein Mischmasch machen und Material + eigene Icons verwenden. Die werden nur einmal geladen und dann gecached.

**Comment by mkay-sh** [comment]
Ich schließe diesen Issue mal. Da wir soweit erstmal alle Icons für Geomat haben und ja auch keine direkte Weiterentwicklung mehr an GeoMat vornehmen, bis es ein neues Backend gibt. Wenn wir dann noch weitere Icons brauchen, können wir entsprechende Issues anlegen.
