### ISSUE TITLE
Unified Image Component

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#605]
Eine Image Komponente für alle Bilder in der APP. Benötigte Features:

- [x] Credits overlay
- [x] Zoom (dzi)
- [x] No Image 
- [ ] Audiofile

Verwendung in:

- [x] ProfileDetail
- [x] ProfileGrid
- [ ] Slideshow
- [ ] Messages

**Comment by mkay-sh** [comment]
Wenn die Credits offen sind und man scrollt werden diese nun geschlossen. Wenn man sie erneut öffnen möchte, muss man doppelt klicken.
Es gibt auch keinen guten Workaround um das zu verhindern. Da müssen wir warten bis https://github.com/angular/components/pull/7950 im nächsten CDK Release ist.

**Comment by sheepyhollow** [comment]
Wie ist denn hier der Status (auch in Bezug auf https://github.com/angular/components/pull/7950)?
Nach den letzten Diskussionn ("media object") - muss oben noch was ergänzt werden?

**Comment by sheepyhollow** [comment]
sollte sich mit Angular 11 erledigen
