### ISSUE TITLE
Bildskalierung

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#611]
Hochformatige Bilder werden in der Galerieansicht noch auf die Breite angepasst und gehen über ihre Box hinaus.
Im offenen Steckbrief werden sie linksbündig ausgerichtet, besser wäre zentriert oder auch in voller Breite.

**Comment by sheepyhollow** [comment]
Es mag sein, dass das auch inhaltlich (mit dem Backend) nicht sauber geklärt ist. Dann sollten wir das mal festnageln; Tim hatte die Frage schon aufgeworfen.

**Comment by mkay-sh** [comment]
Auch in der Galerie wird die #605 Komponente in Zukunft eingebunden. Aber auch da wird es das Problem geben. Lösung wird vermutlich den Style abhängig vom Format unterschiedlich zu setzen. Ansonsten verlieren wir die "möglichst" bildschirmfüllende Variante und haben teilweisee noch seltsamere Bildgrößen.

**Comment by sheepyhollow** [comment]
> Hochformatige Bilder werden in der Galerieansicht noch auf die Breite angepasst

Ich meinte hier die Thumbnails. Dort wird ja nicht die ganze Komponente benutzt, oder?

**Comment by mkay-sh** [comment]
In der Galerie werden nicht die Thumbnails angezeigt. Die wären zu klein. Aber das ist tatsächlich noch eine offene Frage. Müssen wir auch bei den Thumbnails die Credits anzeigen?

**Comment by sheepyhollow** [comment]
Ich denke nicht. Wenn diese offensichtlich auf einen Ort verweisen (Steckbrief), an dem der Copyright-Hinweis zu finden ist, sollte das ausreichen.

**Comment by mkay-sh** [comment]
Dann werde ich in der Galerie zwar die neue Image Komponente verwenden aber Credits etc. deaktivieren.

**Comment by sheepyhollow** [comment]
👍 Man würde sonst vor lauter (c) kein Bild mehr sehen ;-)
