### ISSUE TITLE
[DIVE] Optische Änderungen der Steckbriefe

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/solid-frontend#642]
- [x] **Überarbeiten des Titels:**
     - [x] Artname kursiv bis Klammer, Klammer + Inhalt (Erstbestimmer) normal
     - [x] Anzeigen des Ausgewählten Trivialnamens

- [x] **Umsetzen des Abschnitts "Wissenswertes"** (Immer sichtbare Textbox, gefolgt von eingeklappten drop-down Menüs)
- [ ] **Darstellung der Eigenschaften und Ausprägung im Steckbrief optisch besser trennen**, Mögliche Wege:
     - [ ] Eigenschaft optisch hervorheben (**fett**, _kursiv_, etc.)
     - [ ] Einrücken der Ausprägung
     - [ ] Zeilenabstand zwischen zusammengehörender Eigenschaft und Ausprägung verringern, größerer Abstand zwischen den paaren

**Comment by sheepyhollow** [comment]
@mgrethlein Bitte nachschauen und das issue ggf. updaten.

**Comment by sheepyhollow** [comment]
Können wir das zumachen @mgrethlein @IH0815 oder ist da noch was dran zu tun?

**Comment by mgrethlein** [comment]
@sheepyhollow Können wir dicht machen, ja.

**Comment by sheepyhollow** [comment]
Done.
