### ISSUE TITLE
Ausblenden der Addressleiste im mobilen Browser

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/solid-frontend#666]
Beim herunterscrollen des Fensters im mobilen Browser ausblenden der Adressleiste, sodass mehr von der App angezeigt werden kann.

**Comment by sheepyhollow** [comment]
@mgrethlein Das ist ziemlich tricky und kann beim aktuellen Stand der Frameworks nur mit (unschönen) Hacks bewerkstelligt werden.

**Comment by sheepyhollow** [comment]
Du darfst aber gerne nochmal dran erinnern, aber es sollte im Moment keine Priorität haben.
