### ISSUE TITLE
Quizanswers-Endpoint

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#676]
Wir der `quizanswers`-endpoint benötigt bzw. aktuell genutzt?

**Comment by mkay-sh** [comment]
Nein der wurde frontendseitig noch nie genutzt. Das Backend-Team hat ihn der Vollständigkeit halber implementiert.

**Comment by sheepyhollow** [comment]
@chgad @suehtomit

**Comment by chgad** [comment]
Wie ich gestern gesagt habe. Nur der Vollständigkeit halber. Ich tendiere aber dazu ihn drin zulassen, er stört nicht. Man bedenke, dass (auch wenn mit vmtl. kleiner audience) wir das Paket veröffentlicht haben. Da sollten wir schon zu jedem Model auch die API anbieten.
