### ISSUE TITLE
[GeoMat] API-Abfragen 

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#677]
Aktuell wird unter geomat.uni-frankfurt.de das SOLID-Frontend mit den DivE-Inhalten angezeigt.

**Comment by mkay-sh** [comment]
Stimmt, das lag daran das noch kein SOLID-Backend für Geomat zur Verfügung stand. Jetzt gibt es das also muss ich da noch umstellen.
@chgad warum wurde denn aus dem dev Branch auf Production deployed? Eigentlich ist es doch:
dev -> Staging
master mit tag -> Release

**Comment by chgad** [comment]
Der PR #632 wurde auf `dev` gemerged. Da hatte ich an dem PR nichts geändert.

**Comment by mkay-sh** [comment]
Ja aber laut Pipeline landet das ja im Geomat Staging Directory.
Dann sollte es ja nicht in der Production Env landen.

**Comment by chgad** [comment]
Ach du meinst wegen der Sentryinstanz? Wie ist die denn eingerichtet? Entscheiden Snetry die Instanz anhand der URL? Falls ja, würde es das erklären da die staging app momentan auf `geomat.uni-frankfurt.de` antwortet. Der Router lässt ja `geomat.uni-frankfurt.de/staging` nicht zu, was die ursprünlighe Idee für das staging ENV war.

**Comment by mkay-sh** [comment]
Nee die kommt aus der ENV beim build/deploy. Wo finde ich das "neue" Geomat Backend?

**Comment by chgad** [comment]
Neue API root ist `https://solid-backend.uni-frankfurt.de/geomat/production` bzw. https://solid-backend.uni-frankfurt.de/geomat/staging`
