### ISSUE TITLE
Menü und Kacheln

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#678]
Aus dem Content-Team kam die Frage, ob man einzelne Slideshows im Hamburger-Menü als Unterpunkte einfügen kann, falls es mehr werden als die 2x3 Kacheln auf der Startseite.

Daraus ergibt sich die Fragen:
* sind die Startseiten-Kacheln sinnvoll?
* Wenn ja - ist das 2x3-Grid sinnvoll oder sollten wir einfach (à la Galerie) ein füllendes Grid aufbauen?

**Comment by sheepyhollow** [comment]
Auch und die wichtigere Frage:
* sind Untermenüs überhaupt sinnvoll? Könnte auch zu cluttered sein

**Comment by mkay-sh** [comment]
Die Frage hatte ich vor Monaten schon gestellt und da habt ihr euch gegen ein Untermenü entschieden. Kann das natürlich trotzdem wieder umbauen.

**Comment by sheepyhollow** [comment]
ups... Müssen wir wohl nochmal verhandeln. Ich bin nicht sicher, was guter "App"-Style ist. Es kann ja - theoretisch - beliebig viele Slideshows geben.

**Comment by mkay-sh** [comment]
Nach der Diskussion im Slack können wir den Issue schließen oder? Kachelansicht gibt es ja bereits.

**Comment by sheepyhollow** [comment]
yep
