### ISSUE TITLE
Glossarverlinkung

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#7]
1. Innerhalb des Glossars sollen Verlinkungen möglich sein. Das Linkziel wird per Scrollto angezeigt und optisch hervorgehoben.
2. Ebenso sollen Stichworte aus anderen Komponenten in das Glossar verlinken können, woraufhin das Glossar ausklappt, die richtige Stelle angescrollt und hervorgehoben wird.

**Comment by sheepyhollow** [comment]
Scrollto-Position ist zu überlegen - ca. Mitte des Bildschirms oder oben.

**Comment by mkay-sh** [comment]
Ich würde oben vorschlagen. Das ist dann wenigstens konsistent. Wenn wir die Mitte nehmen fängt es mal höher und mal tiefer an, je nachdem wie groß der Eintrag ist.
Außnahme sind Einträge am Ende des Glossars. Da ist die Position dann an der Stelle, an der auch der Eintrag ist, da die nicht mehr ganz oben sein können.

**Comment by sheepyhollow** [comment]
Verlinkungen innerhalb des Glossars müssen in der DB eingepflegt werden - wie sieht die Syntax hierfür aus? 
Der Pfeil könnte durch entsprechenden Style hinzugefügt werden.
[Da Links aktuell durch `&rarr;` gekennzeichnet sind, könnte man die Ersetzung in der DB auch automatisiert durchführen]

**Comment by sheepyhollow** [comment]
> Ich würde oben vorschlagen. Das ist dann wenigstens konsistent. 
Make it so.
"Mitte" wäre mit ein paar Rechentricks auch realisierbar (mit entsprechenden Ausnahmen an Anfang/Ende), aber unnötig umständlich.

**Comment by mkay-sh** [comment]
Kann erst umgesetzt werden, wenn die notwendigen Anpassungen im Backend vorgenommen wurden. [https://github.com/GeoMatDigital/django-geomat/issues/291](url)

**Comment by mkay-sh** [comment]
Zusätzlich sollten mit der Verlinkungsfunktion auch die Links aus dem Bestimmungshelfer wieder funktionieren.

**Comment by sheepyhollow** [comment]
Wir hatten uns ja gegen eine Suche entschieden weil die alphabetische Sortierung das überflüssig macht.

Was wäre aber damit, durch die Buchstaben der Tastatur ein `scrollto` auszulösen? Schnickschnack, aber nett. Kann man angehen, wenn die Verlinkung funktioniert.

**Comment by mkay-sh** [comment]
Erste Variante implementiert. Styling muss noch angepasst werden. Ich weiß nicht ob das Scrolling per Tastatur wirklich sinnvoll ist. Im Rest der App haben wir auch keine Keyboardshortcuts.

**Comment by mkay-sh** [comment]
Soweit so gut;)
