### ISSUE TITLE
Drag n Drop Quizkomponente

### ISSUE THREAD

**Issue by mkay-sh** [zentrumnawi/solid-frontend#708]
Für das Quiz soll es zusätzlich zu den bereits vorhandenen Single- und Multiple-Choice-Fragen noch eine Drag-and-Drop-Frage geben, in der der Nutzer eine Liste von Einträgen in eine Reihenfolge bringen soll.

Die Frage soll als Pull-Request auf dem Branch `feature/quiz-abstraction` durchgeführt werden. Dabei ist nur die `DragAndDropQuestionComponent` zu implementieren.

Eine [leere Komponente `./libs/solid/quiz/src/lib/components/drag-and-drop-choice-question`](https://github.com/zentrumnawi/solid-frontend/tree/feature/quiz-abstraction/libs/solid/quiz/src/lib/components/drag-and-drop-choice-question) mit den benötigten Daten gibt es bereits. 

**Technische Anforderungen**
1. Einen Fork von diesem Repository (`solid-frontend`) erstellen.
2. Den Branch `feature/quiz-abstraction` auschecken.
3. Auf dem Entwicklungsrechner muss **nodejs 12.*** und der **yarn** Package Manager installiert werden.
4. `yarn` ausführen um die Abhängigkeiten zu installieren.
5. Mit `yarn nx serve dive` lässt sich Anwendung im Entwicklungsmodus starten (Port 4200).
6. Komponente entwickeln
    Für die Drag-and-Drop-Funktionalität bietet sich die entsprechende Komponente aus dem Angular CDK an [https://material.angular.io/cdk/drag-drop/overview#reordering-lists](https://material.angular.io/cdk/drag-drop/overview#reordering-lists).
7. Commit erstellen
8. PullRequest auf unser Repository (Branch `feature/quiz-abstraction`) erstellen oder einen Link zum Fork bereitstellen.

**Inhaltliche Anforderungen**
1. Das Quiz (Selbsttest) in der SOLID-Basis-App soll um Drag-and-Drop erweitert werden.
2. Die Anordnung der Elemente soll bei jedem Aufruf zufällig sein.
3. Das Feedback (richtig/falsch) soll als Farbe (rot/grün) _und_ mit einem Symbol (&#10003;/&#10007;) dargestellt werden.
4. Zusätzlich soll ein Text-Feedback ausgegeben werden (siehe Datenmodell).
5. (Zusatzaufgabe): Machen Sie einen Vorschlag, wie auch eine _relative_ richtige Ordnung ausgewertet und angezeigt werden kann (z.B. 5-1-2-3-4 : die Reihenfolge von 1-4 istkorrekt, aber die 5 steht an der falschen Stelle, das ist nicht vollständig richtig, aber auch nicht ganz falsch).

Bei technischen Fragen stehe ich zur Verfügung.

**Comment by sheepyhollow** [comment]
moved to #744
