### ISSUE TITLE
Slideshow active

### ISSUE THREAD

**Issue by suehtomit** [zentrumnawi/solid-frontend#727]
Abhängig vom active-Wert wird eine Slideshow in der Übersicht angezeigt oder nicht.

**Comment by sheepyhollow** [comment]
Rückfrage @suehtomit - sollte das nicht im Backend passieren? Wenn nicht `active`, dann ist es nicht im endpoint.

**Comment by suehtomit** [comment]
Stimmt, das ist eine gute Anmerkung! Wie siehst du das @chgad, gibt es einen Grund eine nicht aktive Slideshow im Endpoint bereitzustellen? Falls nein, passe ich den Endpoint an und das Issue hier ist erledigt.

**Comment by sheepyhollow** [comment]
wie besprochen @suehtomit
