### ISSUE TITLE
Navigationsleiste Stammbaum

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/solid-frontend#734]
Im Augenblick fehlen die Miniaturansichten in der Stammbaumnavigation.
In der Galerieansicht sind sie vorhanden.

Ist es möglich die Navigationsleiste als aus- und einklapbares Element bei einem breiten Bildschirm zu gestalten?

**Comment by sheepyhollow** [comment]
Ich würde sagen, die Miniaturansichten sind da.

Bezüglich einklappbar müssten wir sehen - es klappt ja auch automatisch weg, wenn der Bildschirm zu klein ist. 
Allerdings bräuchten wir dann auch wieder eine Schaltfläche etc.

**Comment by sheepyhollow** [comment]
Wenn Ihr (@mgrethlein @IH0815) Ideen habt, wie die Bedienung aussehen könnte, dann dürft Ihr gerne Vorschläge machen.

**Comment by sheepyhollow** [comment]
Ich  nehm's zurück - in der Baumansicht wird auf "no image" defaulted.

**Comment by sheepyhollow** [comment]
Aktuell verweist `images` in https://github.com/zentrumnawi/solid-frontend/blob/9e1f32aabbe3a06f3180f429f566f81fd38d9a96/libs/solid/profile/src/lib/components/tree/tree.component.ts#L108 auf ein leeres Array. 

To-Do: uncomment line 109 (`images: node.images`) and remove line 108; check for side effects.
What about line 33 in the ´EntryNode´?

**Comment by sheepyhollow** [comment]
Fixed in #839
