### ISSUE TITLE
Fix Slideshow component

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#769]
The slideshow component needs some adaptation to the last version of the endpoint.

All images in SOLID are now based on the `PhotographModel`.
- The `PhotographModel` is defined/exported in `/libs/solid/core/src/lib/models/photograph.model.ts`
- The `SlideshowPages` still has an internal `SIideshowImage`-Model containing several additional fields (caption, position) but uses the `PhotographModel` for the eventual image. 
- [x] adapt the `slideshow.model.ts` to the actual endpoint (check swagger or raw endpoint JSON output)
  - [x] the `img` element in `Slideshow` will be _renamed_ to `title_image` (and contains a `PhotographModel` object).
  - [x] `slideshow.state.ts` needs updating, too
- [x] the `slideshow-select`-component should use the `.thumbnail` image
- [x] uncomment the image block  in the `slideshow`-component and fix all references to fit the model*
  - [x] use the `.large` image

\* It may look confusing since the `*ngFor` variable to iterate the images is named `img`. So we might get stuff like `img.image.img.large`.

**Comment by sheepyhollow** [comment]
We should discuss if the preview image in slideshow-select is required (by the backend) or if we fill in some default value if no image is set.

**Comment by sheepyhollow** [comment]
We should also think about the field names; image.img.img is not so pretty. 
I also raised the issue with @suehtomit

**Comment by suehtomit** [comment]
As discussed the slideshow endpoint will provide the image source in `slideshow.title_image.img`.

**Comment by sheepyhollow** [comment]
Thanks! I have re-formulated the issue.
