### ISSUE TITLE
Slideshow Navigation inkonsistent

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#903]
Es gibt Inkonsistenzen bei der Navigation (und ich kann sie mir aus dem Backend/den Seiten der Slideshows gerade nicht erklären): 

Es gibt teilweise einen Zurück-Pfeil auf der ersten Seite einer Slideshow (ohne Funktion; #788 , z.B. Div-e/Darstellung Test1 oder AIS/Scherbenzuweisung) & teilweise nicht (z.B. Div-e/Bestimmen mit Bestimmtheit). 

Bei AIS/Scherbenzuweisung fehlt mitten in der Slideshow (Slide 3 "Rand/Lippe" der Zurück-Pfeil, sodass es, wenn man sich zurückklickt, so wirkt, als sei die Slideshow an der Stelle vorbei.

**Comment by sheepyhollow** [comment]
Aktuell wird die `page.id` direkt zum Ansprechen der Seiten verwendet - die werden aber fortlaufend vergeben und müssen innerhalb einer Slideshow nicht mal aufeinanderfolgen. 
- [ ] To-Do: Alle Vorkommen von `page.id` ändern zu `page.position` (`slideshow.component.html`)

**Comment by sheepyhollow** [comment]
Wir sollten das mit #788 in einem Fix gemeinsam lösen.
