### ISSUE TITLE
URL-Routing

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#906]
Wir brauchen eine Möglichkeit, Steckbriefe (profiles) über einen Direktlink zu erreichen, da Planty mit QR-Codes im Weinberg arbeiten will. Zur Zeit geht das nicht.

Wie ermöglichen wir den Zugriff auf "Deeplinks"? Was muss dafür getan werden?

**Comment by sheepyhollow** [comment]
@mkay-sh - das hatte ich beim letzten Meeting vergessen. Vielleicht kannst Du uns mal eine Einschätzung geben, wie aufwändig das ist oder ob das sogar im Prinzip schon funktioniert. Bei mir "funktioniert" es, aber nur dank Cache. Nach einem API-Request/force Reload fliegt es aus der Kurve.

**Comment by mkay-sh** [comment]
Also grundsätzlich sollte das bereits funktionieren. Allerdings ist die aktuelle View (Grid bzw. Tree) teil der Url. Eventuell müsste man die dann rausprökeln oder sich für eine Variante in den QR-Codes entscheiden. Bei mir schlägt ein Force-Reload mit nem nginx 404 fehl. Das liegt dann vermutlich daran, dass der nicht korrekt auf die index.html redirected. Eventuell kann @chgad was dazu sagen.

**Comment by sheepyhollow** [comment]
Ich fände es okay, eine Variante zu wählen - auf (kleinen) Mobilgeräten werden Baum oder Grid sowieso nicht angezeigt. Macht den Link auch nicht so arg länger.

**Comment by chgad** [comment]
> Eventuell kann @chgad was dazu sagen.
Jo, also ich hab's echt simpel gehalten:

```
server {
    server_name dive.uni-frankfurt.de;
    root /home/zentrumnawi/dive-frontend-production/;

    location / {
      try_files $uri $uri/ index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dive.uni-frankfurt.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dive.uni-frankfurt.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = dive.uni-frankfurt.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name dive.uni-frankfurt.de;
    listen 80;
    return 404; # managed by Certbot
}
```

denke mal, dass es auch daran liegt. aber wie leite ich die URL korrekt an die index.html weiter? Also wie gebe ich die Bestandteile weiter? URI parameter?

**Comment by sheepyhollow** [comment]
Ich nehme an, die Frage geht an @mkay-sh

**Comment by sheepyhollow** [comment]
mit `/index.html` funktioniert es - danke @chgad
