### ISSUE TITLE
Anzeigefehler in der Kachelansicht der Steckbriefe

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#930]
Bei langen Namen der Objekte in den Steckbriefen gibt es einen Anzeigefehler: Das entsprechende Foto wird nicht an die Kachelgröße angepasst, sondern ragt darüber hinaus. 

![grafik](https://user-images.githubusercontent.com/66634630/116670558-25dc7b00-a9a0-11eb-9ff9-f60f090b7d83.png)

**Comment by sheepyhollow** [comment]
Vorläufig gelöst, aber noch nicht sauber.

**Comment by sheepyhollow** [comment]
Noch etwas verbessert - es werden nun einfach die Thumbnails verwendet. Dabei haben die Kacheln viel Weißraum, aber es ist einheitlicher. 

Ich würde vorschlagen, diesen Pfad weiter zu beschreiten, falls es für diese Vorschau nicht so wichtig ist, z.B. einen Baum in seiner Höhe zu sehen.

Ich würde aber dafür sprechen, die Auswahl der Vorschaubilder mittelfristig als eigenes Thema anzugehen. Notfalls durch ein explizites Vorschaubild. 

Noch schöner: Grundsätzlich keine hochformatigen Bilder verwenden. Schwierig bei Bäumen, aber z.B. der Holunder sieht auch gut aus.
