### ISSUE TITLE
Slideshow Scroll-"Problem" (mobile Geräte)

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/solid-frontend#931]
Auf mobilen Geräten muss man, wenn man sich auf einer Slideshowseite bewegt sehr viel scrollen & vor allem um auf die nächste Slide zu kommen muss man wieder zur Navigation ganz nach oben scrollen. 
Wie können wir das anders lösen, sodass die Bedienung am mobilen Gerät praktischer wird? 

Erste Idee: Die Navigationsleiste fixieren, sodass sie immer sichtbar ist. Das nimmt aber natürlich auch Platz ein, der sonst für die Inhalte der Slideshow genutzt werden könnte.

**Comment by sheepyhollow** [comment]
Theoretisch gibt es da die Lösung, dass die Titelzeile beim Runterscrollen verschwindet und bei der ersten Scrollbewegung nach oben sofort erscheint. Aber... 🤷‍♂️

**Comment by anhnguyen-98** [comment]
Close via #1215
