### ISSUE TITLE
Slideshow link behaviour

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#941]
Links in der Slideshow öffnen sich im gleichen Fenster, d.h. man verlässt SOLID.

Das kann evtl. Nachteile haben - vor allem, wenn das Routing (#906) nicht unbedingt wieder sauber zurückführt.

Es gibt verschiedene Lösungsstrategien
* Beim Erstellen einer Slideshow für Links HTML statt Markdown benutzen
* `target="_blank` erzwingen (wahrscheinlich schwierig, weil die Umsetzung durch Markdown gemacht wird)
*  Luxus-Lösung: Es öffnet sich ein Dialog, der dem User die Wahl lässt, ob im gleichen oder in einem neuen Fenster geöffnet wird.

**Comment by anhnguyen-98** [comment]
@sheepyhollow wo genau haben wir die Links im Slideshow? Ich konnte die nicht finden.

**Comment by sheepyhollow** [comment]
Wir haben Links in der Dive-Slideshow, z.B. hier: https://dive.uni-frankfurt.de/slideshow/5

Wir können das Issue aber auch zurückstellen.

**Comment by anhnguyen-98** [comment]
Einheitliche Lösung: HTML Links beim Eingeben des Contents mit `target="_blank"`
