### ISSUE TITLE
Profile Images Swipe

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#966]
Die verschiedenen Bilder in einem Steckbriefen sollten sowohl über den Thumbnail, als auch per Swipe navigierbar sein

**Comment by sheepyhollow** [comment]
Ging das nicht bei GeoMat schonmal?

**Comment by sheepyhollow** [comment]
Das heißt: 
* Swipe auf den Thumbnails = Scroll thumbnails
* Swipe auf das Bild = nächtes Bild (und Highlight des nächsten Thumbnails)

**Comment by sheepyhollow** [comment]
@mkay-sh vielleicht kannst Du uns hier einen Tipp geben:
Konnten wir nicht mal swipe In Slideshow und Profiles? Aktuell funktioniert das nicht. 
Brauchen wir dafür eine eigenen Library (z.B: swipeJS) oder kann man das mit HammerGesture umsetzen? Das ist ja schon im Projekt.

**Comment by sheepyhollow** [comment]
Sollen wir das offenlassen für ein "schöneres" Swipe? @anhnguyen-98 
Ansonsten: schließen und ein neues issue schreiben.

**Comment by anhnguyen-98** [comment]
> Sollen wir das offenlassen für ein "schöneres" Swipe? @anhnguyen-98
> Ansonsten: schließen und ein neues issue schreiben.

Ich glaub wir schließen erstmal es und falls nötig machen wir ein neues issue.

**Comment by sheepyhollow** [comment]
done!
