### ISSUE TITLE
Remove Title-Formatter

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#970]
Wird der Title-Formatter noch gebraucht, wenn wir markdown-fields haben ? (&rarr; #501)

https://github.com/zentrumnawi/solid-frontend/tree/dev/libs/solid/profile/di

**Comment by sheepyhollow** [comment]
Der Title-Formatter wird nicht mehr gebraucht, das können wir im Content und mit Markdown regeln.

- [ ] Title-Formatter aus dem Code entfernen
- [ ] ein Flag einführen, mit dem (in skeleton) definiert werden kann, ob das `title`-Feld als Markdown interpretiert wird
- [ ] Markdown-spezifische Zeichen escapen
( - [ ] dem Backend bescheid geben, dass die Formatierung des Titels nicht im Frontend erledigt wird)

**Comment by anhnguyen-98** [comment]
closed in [713cfcf](https://github.com/zentrumnawi/solid-frontend/commit/713cfcff4d62a537885280335f3ffcd8ee4b101f)
