### ISSUE TITLE
Slideshow toolbar

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#971]
In den Slideshows sollten einige Änderungen eingerichtet werden:

- [ ] es soll eine Toolbar geben (ähnlich wie die Toolbar bei den Steckbriefen)
  - die Toolbar soll den Titel der Seite und den Titel der Slideshow (als subtitle) sowie die Navigationselemente enthalten
- [ ] Es soll einen _progress bar_ oder eine Seitenanzeige (Seite n/m) geben
  - z.B. schmal unter der Toolbar. 
- [ ] Die Toolbar sollte "sticky" sein, wenn möglich

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/133420400-81b87dff-4c26-446b-90fc-4df7ee1138df.png)

So ungefähr könnte es aussehen.

**Comment by anhnguyen-98** [comment]
Close via #1215
