### ISSUE TITLE
Slideshow Categories

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#976]
Die Slideshows werden um ein Feld `category` erweitert.

Damit soll in der Slideshow-Übersicht (slidsehow-select) eine Unterteilung möglich sein:
- [ ] Jede Kategorie soll mit einer Überschrift und einer mat-line angezeigt werden
- [ ] Optional: wenn es nur eine Kategorie gibt werden die Slideshows ohne Überschrift direkt angezeigt

**Comment by sheepyhollow** [comment]
Wie gehen wir mit dem Fall um, dass einige Slideshows eine Kategorie haben und andere nicht? @kerstinhartmann 
`category` als required Setzen ist vmtl. nicht sinnvoll...

**Comment by kerstinhartmann** [comment]
Vorstellen könnte ich mir Folgendes: 
1. Entweder sollten zuerst alle Slideshows gelistet werden, die keiner Kategorie zugeordnet sind und anschließend die Slideshows mit ihrer entsprechenden Kategorie 
Oder 
2. alle unkategorisierten Slideshows werden in einer weiteren Kategorie "Weiteres" (oder "Sonstiges" oder so) zusammengefasst angezeigt. Das wüde ich dann eher als letzte Kategorie in der Auflistung anzeigen. 

_Wie wird die Kategorie-Reihenfolge bestimmt? Wie beeinflusst das die aktuelle Sortierung der Slideshows (Position)?_

**Comment by kerstinhartmann** [comment]
Wenn es nur eine Kategorie gibt, sollte diese vielleicht doch auch angezeigt werden. Denn die Kategorie wurde dann ja vermutlich aus einem inhaltlichen Grund angelegt. (Wenn die Kategorie inhaltlich nicht sinnvoll wäre, gibt es ja schließlich die Möglichkeit keine Kategorie anzugeben.)
Wenn es aber keine Kategorie gibt, sollten die Slideshows ohne Überschrift direkt angezeigt werden. 

Was passiert, wenn es nur eine Slideshow aber mit Kategorie gibt?

**Comment by sheepyhollow** [comment]
Das category Feld müsste bereits in Arbeit sein - bitte hierzu chgad fragen.

**Comment by sheepyhollow** [comment]
`category` ist nun in den Staging und Production Frontends von _ais_, _planty_ und _geomat_ verfügbar.

Drei Punkte sind mir noch nicht klar:
* es gibt nur eine `category`, in der alle Slideshows sind
* bzw. es gibt Slideshows, aber keine `category` (endpoint liefert `[]` &rarr; aktuell bei Planty der Fall)
* Es gibt Slideshows mit und ohne `category`

**Comment by sheepyhollow** [comment]
Okay... ich glaube, wir konvergieren langsam zum einem finalen Ergebnis....

1. Es gibt keine Kategorie "Sonstiges" - alle slideshows müssen einen Eintrag bei `categories` haben
2. Wenn es nur eine Slideshow gibt, wird diese direkt angezeigt (erledigt)
3. Wenn es nur eine Kategorie gibt, wird direkt `slideshow-select` angezeigt 

@kerstinhartmann bitte nochmal bestätigen, dass ich das richtig wiedergegeben habe
@anhnguyen-98 kannst Du 3. noch einbauen und dann mergen?

**Comment by kerstinhartmann** [comment]
genau, so soll's sein

Zur Präzisierung 2.: Wenn es nur eine Slideshow **innerhalb einer Kategorie** gibt, dann wird bei Auswahl der Kategorie direkt die Slideshow angezeigt.

**Comment by anhnguyen-98** [comment]
Close via #1215
